// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package query

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.getSystemByNameStmt, err = db.PrepareContext(ctx, getSystemByName); err != nil {
		return nil, fmt.Errorf("error preparing query GetSystemByName: %w", err)
	}
	if q.getSystemsInRectStmt, err = db.PrepareContext(ctx, getSystemsInRect); err != nil {
		return nil, fmt.Errorf("error preparing query GetSystemsInRect: %w", err)
	}
	if q.insertShipStmt, err = db.PrepareContext(ctx, insertShip); err != nil {
		return nil, fmt.Errorf("error preparing query InsertShip: %w", err)
	}
	if q.insertSystemStmt, err = db.PrepareContext(ctx, insertSystem); err != nil {
		return nil, fmt.Errorf("error preparing query InsertSystem: %w", err)
	}
	if q.truncateShipsStmt, err = db.PrepareContext(ctx, truncateShips); err != nil {
		return nil, fmt.Errorf("error preparing query TruncateShips: %w", err)
	}
	if q.truncateSystemsStmt, err = db.PrepareContext(ctx, truncateSystems); err != nil {
		return nil, fmt.Errorf("error preparing query TruncateSystems: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.getSystemByNameStmt != nil {
		if cerr := q.getSystemByNameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSystemByNameStmt: %w", cerr)
		}
	}
	if q.getSystemsInRectStmt != nil {
		if cerr := q.getSystemsInRectStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSystemsInRectStmt: %w", cerr)
		}
	}
	if q.insertShipStmt != nil {
		if cerr := q.insertShipStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertShipStmt: %w", cerr)
		}
	}
	if q.insertSystemStmt != nil {
		if cerr := q.insertSystemStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertSystemStmt: %w", cerr)
		}
	}
	if q.truncateShipsStmt != nil {
		if cerr := q.truncateShipsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing truncateShipsStmt: %w", cerr)
		}
	}
	if q.truncateSystemsStmt != nil {
		if cerr := q.truncateSystemsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing truncateSystemsStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                   DBTX
	tx                   *sql.Tx
	getSystemByNameStmt  *sql.Stmt
	getSystemsInRectStmt *sql.Stmt
	insertShipStmt       *sql.Stmt
	insertSystemStmt     *sql.Stmt
	truncateShipsStmt    *sql.Stmt
	truncateSystemsStmt  *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                   tx,
		tx:                   tx,
		getSystemByNameStmt:  q.getSystemByNameStmt,
		getSystemsInRectStmt: q.getSystemsInRectStmt,
		insertShipStmt:       q.insertShipStmt,
		insertSystemStmt:     q.insertSystemStmt,
		truncateShipsStmt:    q.truncateShipsStmt,
		truncateSystemsStmt:  q.truncateSystemsStmt,
	}
}
