// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: jump_gates.sql

package query

import (
	"context"
)

const insertJumpGate = `-- name: InsertJumpGate :exec
INSERT INTO jump_gates (
	waypoint, connects_to
) VALUES (
	?, ?
)
`

type InsertJumpGateParams struct {
	Waypoint   string
	ConnectsTo string
}

func (q *Queries) InsertJumpGate(ctx context.Context, arg InsertJumpGateParams) error {
	_, err := q.exec(ctx, q.insertJumpGateStmt, insertJumpGate, arg.Waypoint, arg.ConnectsTo)
	return err
}

const truncateJumpGates = `-- name: TruncateJumpGates :exec
DELETE FROM jump_gates
`

func (q *Queries) TruncateJumpGates(ctx context.Context) error {
	_, err := q.exec(ctx, q.truncateJumpGatesStmt, truncateJumpGates)
	return err
}
