// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package query

type JumpGate struct {
	Waypoint   string
	ConnectsTo string
}

type System struct {
	Symbol   string
	X        int64
	Y        int64
	Type     string
	Factions string
}

type Waypoint struct {
	Symbol  string
	System  string
	Orbits  interface{}
	X       int64
	Y       int64
	Type    string
	Charted bool
}
