// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package query

type Ship struct {
	Symbol          string
	CurrentSystem   string
	CurrentWaypoint string
}

type System struct {
	Symbol   string
	X        int64
	Y        int64
	Type     string
	Factions string
}
