// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: ships.sql

package query

import (
	"context"
)

const insertShip = `-- name: InsertShip :exec
INSERT INTO ships (
		symbol,	current_system, current_waypoint
) VALUES (
	?, ?, ?
)
`

type InsertShipParams struct {
	Symbol          string
	CurrentSystem   string
	CurrentWaypoint string
}

func (q *Queries) InsertShip(ctx context.Context, arg InsertShipParams) error {
	_, err := q.exec(ctx, q.insertShipStmt, insertShip, arg.Symbol, arg.CurrentSystem, arg.CurrentWaypoint)
	return err
}

const truncateShips = `-- name: TruncateShips :exec
DELETE FROM ships
`

func (q *Queries) TruncateShips(ctx context.Context) error {
	_, err := q.exec(ctx, q.truncateShipsStmt, truncateShips)
	return err
}
