// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: systems.sql

package query

import (
	"context"
)

const getSystemByName = `-- name: GetSystemByName :one
;

SELECT x, y FROM systems
WHERE symbol = ?1
`

type GetSystemByNameRow struct {
	X int64
	Y int64
}

func (q *Queries) GetSystemByName(ctx context.Context, systemName string) (GetSystemByNameRow, error) {
	row := q.queryRow(ctx, q.getSystemByNameStmt, getSystemByName, systemName)
	var i GetSystemByNameRow
	err := row.Scan(&i.X, &i.Y)
	return i, err
}

const getSystemsInRect = `-- name: GetSystemsInRect :many
SELECT
	  systems.symbol, systems.x, systems.y, systems.type, systems.factions
	, CAST(IFNULL(GROUP_CONCAT(wp_connected.system, ','), '') AS TEXT) AS connected_systems
FROM systems
JOIN waypoints
	ON systems.symbol = waypoints.system
LEFT JOIN jump_gates
	ON waypoints.symbol = jump_gates.waypoint
LEFT JOIN waypoints wp_connected
	ON wp_connected.symbol = jump_gates.connects_to
WHERE TRUE
	AND systems.x >= ?1 AND systems.x <= ?2
	AND systems.y >= ?3 AND systems.y <= ?4
GROUP BY
	  systems.symbol
	, systems.x
	, systems.y
	, systems.type
	, factions
`

type GetSystemsInRectParams struct {
	XMin int64
	XMax int64
	YMin int64
	YMax int64
}

type GetSystemsInRectRow struct {
	System           System
	ConnectedSystems string
}

func (q *Queries) GetSystemsInRect(ctx context.Context, arg GetSystemsInRectParams) ([]GetSystemsInRectRow, error) {
	rows, err := q.query(ctx, q.getSystemsInRectStmt, getSystemsInRect,
		arg.XMin,
		arg.XMax,
		arg.YMin,
		arg.YMax,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSystemsInRectRow{}
	for rows.Next() {
		var i GetSystemsInRectRow
		if err := rows.Scan(
			&i.System.Symbol,
			&i.System.X,
			&i.System.Y,
			&i.System.Type,
			&i.System.Factions,
			&i.ConnectedSystems,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasSystemsRows = `-- name: HasSystemsRows :one
SELECT EXISTS (SELECT 1 FROM systems) AS "exists"
`

func (q *Queries) HasSystemsRows(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.hasSystemsRowsStmt, hasSystemsRows)
	var exists int64
	err := row.Scan(&exists)
	return exists, err
}

const insertSystem = `-- name: InsertSystem :exec
INSERT INTO systems (
	symbol, x, y, type, factions	
) VALUES (
	?, ?, ?, ?, ?
)
`

type InsertSystemParams struct {
	Symbol   string
	X        int64
	Y        int64
	Type     string
	Factions string
}

func (q *Queries) InsertSystem(ctx context.Context, arg InsertSystemParams) error {
	_, err := q.exec(ctx, q.insertSystemStmt, insertSystem,
		arg.Symbol,
		arg.X,
		arg.Y,
		arg.Type,
		arg.Factions,
	)
	return err
}

const truncateSystems = `-- name: TruncateSystems :exec
DELETE FROM systems
`

func (q *Queries) TruncateSystems(ctx context.Context) error {
	_, err := q.exec(ctx, q.truncateSystemsStmt, truncateSystems)
	return err
}
