// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: systems.sql

package query

import (
	"context"
)

const getSystemByName = `-- name: GetSystemByName :one
SELECT x, y FROM systems
WHERE symbol = ?1
`

type GetSystemByNameRow struct {
	X int64
	Y int64
}

func (q *Queries) GetSystemByName(ctx context.Context, systemName string) (GetSystemByNameRow, error) {
	row := q.queryRow(ctx, q.getSystemByNameStmt, getSystemByName, systemName)
	var i GetSystemByNameRow
	err := row.Scan(&i.X, &i.Y)
	return i, err
}

const getSystemsInRect = `-- name: GetSystemsInRect :many
SELECT
	systems.symbol, systems.x, systems.y, systems.type, systems.factions, COUNT(ships.symbol) AS ship_count
FROM systems
LEFT JOIN ships
	ON ships.current_system = systems.symbol
WHERE TRUE
	AND x >= ?1 AND x <= ?2
	AND y >= ?3 AND y <= ?4
GROUP BY systems.symbol, x, y, type, factions
`

type GetSystemsInRectParams struct {
	XMin int64
	XMax int64
	YMin int64
	YMax int64
}

type GetSystemsInRectRow struct {
	System    System
	ShipCount int64
}

func (q *Queries) GetSystemsInRect(ctx context.Context, arg GetSystemsInRectParams) ([]GetSystemsInRectRow, error) {
	rows, err := q.query(ctx, q.getSystemsInRectStmt, getSystemsInRect,
		arg.XMin,
		arg.XMax,
		arg.YMin,
		arg.YMax,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSystemsInRectRow{}
	for rows.Next() {
		var i GetSystemsInRectRow
		if err := rows.Scan(
			&i.System.Symbol,
			&i.System.X,
			&i.System.Y,
			&i.System.Type,
			&i.System.Factions,
			&i.ShipCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertSystem = `-- name: InsertSystem :exec
INSERT INTO systems (
	symbol, x, y, type, factions	
) VALUES (
	?, ?, ?, ?, ?
)
`

type InsertSystemParams struct {
	Symbol   string
	X        int64
	Y        int64
	Type     string
	Factions string
}

func (q *Queries) InsertSystem(ctx context.Context, arg InsertSystemParams) error {
	_, err := q.exec(ctx, q.insertSystemStmt, insertSystem,
		arg.Symbol,
		arg.X,
		arg.Y,
		arg.Type,
		arg.Factions,
	)
	return err
}

const truncateSystems = `-- name: TruncateSystems :exec
;

DELETE FROM systems
`

func (q *Queries) TruncateSystems(ctx context.Context) error {
	_, err := q.exec(ctx, q.truncateSystemsStmt, truncateSystems)
	return err
}
