// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: waypoints.sql

package query

import (
	"context"
)

const insertWaypoint = `-- name: InsertWaypoint :exec
INSERT INTO waypoints (
	symbol, system, x, y, orbits, type
) VALUES (
	?, ?, ?, ?, ?, ?
)
`

type InsertWaypointParams struct {
	Symbol string
	System string
	X      int64
	Y      int64
	Orbits interface{}
	Type   string
}

func (q *Queries) InsertWaypoint(ctx context.Context, arg InsertWaypointParams) error {
	_, err := q.exec(ctx, q.insertWaypointStmt, insertWaypoint,
		arg.Symbol,
		arg.System,
		arg.X,
		arg.Y,
		arg.Orbits,
		arg.Type,
	)
	return err
}

const truncateWaypoints = `-- name: TruncateWaypoints :exec
DELETE FROM waypoints
`

func (q *Queries) TruncateWaypoints(ctx context.Context) error {
	_, err := q.exec(ctx, q.truncateWaypointsStmt, truncateWaypoints)
	return err
}
