// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package api

import (
	"encoding/json"
	"time"
)

const (
	AgentTokenScopes = "AgentToken.Scopes"
)

// Defines values for ActivityLevel.
const (
	GROWING    ActivityLevel = "GROWING"
	RESTRICTED ActivityLevel = "RESTRICTED"
	STRONG     ActivityLevel = "STRONG"
	WEAK       ActivityLevel = "WEAK"
)

// Defines values for ContractType.
const (
	ContractTypePROCUREMENT ContractType = "PROCUREMENT"
	ContractTypeSHUTTLE     ContractType = "SHUTTLE"
	ContractTypeTRANSPORT   ContractType = "TRANSPORT"
)

// Defines values for FactionSymbol.
const (
	FactionSymbolAEGIS    FactionSymbol = "AEGIS"
	FactionSymbolANCIENTS FactionSymbol = "ANCIENTS"
	FactionSymbolASTRO    FactionSymbol = "ASTRO"
	FactionSymbolCOBALT   FactionSymbol = "COBALT"
	FactionSymbolCORSAIRS FactionSymbol = "CORSAIRS"
	FactionSymbolCOSMIC   FactionSymbol = "COSMIC"
	FactionSymbolCULT     FactionSymbol = "CULT"
	FactionSymbolDOMINION FactionSymbol = "DOMINION"
	FactionSymbolECHO     FactionSymbol = "ECHO"
	FactionSymbolETHEREAL FactionSymbol = "ETHEREAL"
	FactionSymbolGALACTIC FactionSymbol = "GALACTIC"
	FactionSymbolLORDS    FactionSymbol = "LORDS"
	FactionSymbolOBSIDIAN FactionSymbol = "OBSIDIAN"
	FactionSymbolOMEGA    FactionSymbol = "OMEGA"
	FactionSymbolQUANTUM  FactionSymbol = "QUANTUM"
	FactionSymbolSHADOW   FactionSymbol = "SHADOW"
	FactionSymbolSOLITARY FactionSymbol = "SOLITARY"
	FactionSymbolUNITED   FactionSymbol = "UNITED"
	FactionSymbolVOID     FactionSymbol = "VOID"
)

// Defines values for FactionTraitSymbol.
const (
	FactionTraitSymbolADAPTABLE               FactionTraitSymbol = "ADAPTABLE"
	FactionTraitSymbolAGGRESSIVE              FactionTraitSymbol = "AGGRESSIVE"
	FactionTraitSymbolBOLD                    FactionTraitSymbol = "BOLD"
	FactionTraitSymbolBRUTAL                  FactionTraitSymbol = "BRUTAL"
	FactionTraitSymbolBUREAUCRATIC            FactionTraitSymbol = "BUREAUCRATIC"
	FactionTraitSymbolCAPITALISTIC            FactionTraitSymbol = "CAPITALISTIC"
	FactionTraitSymbolCLAN                    FactionTraitSymbol = "CLAN"
	FactionTraitSymbolCOLLABORATIVE           FactionTraitSymbol = "COLLABORATIVE"
	FactionTraitSymbolCOMMERCIAL              FactionTraitSymbol = "COMMERCIAL"
	FactionTraitSymbolCOOPERATIVE             FactionTraitSymbol = "COOPERATIVE"
	FactionTraitSymbolCURIOUS                 FactionTraitSymbol = "CURIOUS"
	FactionTraitSymbolDARING                  FactionTraitSymbol = "DARING"
	FactionTraitSymbolDEFENSIVE               FactionTraitSymbol = "DEFENSIVE"
	FactionTraitSymbolDEXTEROUS               FactionTraitSymbol = "DEXTEROUS"
	FactionTraitSymbolDISTRUSTFUL             FactionTraitSymbol = "DISTRUSTFUL"
	FactionTraitSymbolDIVERSE                 FactionTraitSymbol = "DIVERSE"
	FactionTraitSymbolDOMINANT                FactionTraitSymbol = "DOMINANT"
	FactionTraitSymbolDOMINION                FactionTraitSymbol = "DOMINION"
	FactionTraitSymbolENTREPRENEURIAL         FactionTraitSymbol = "ENTREPRENEURIAL"
	FactionTraitSymbolESTABLISHED             FactionTraitSymbol = "ESTABLISHED"
	FactionTraitSymbolEXILES                  FactionTraitSymbol = "EXILES"
	FactionTraitSymbolEXPLORATORY             FactionTraitSymbol = "EXPLORATORY"
	FactionTraitSymbolFLEETING                FactionTraitSymbol = "FLEETING"
	FactionTraitSymbolFLEXIBLE                FactionTraitSymbol = "FLEXIBLE"
	FactionTraitSymbolFORSAKEN                FactionTraitSymbol = "FORSAKEN"
	FactionTraitSymbolFRAGMENTED              FactionTraitSymbol = "FRAGMENTED"
	FactionTraitSymbolFREEMARKETS             FactionTraitSymbol = "FREE_MARKETS"
	FactionTraitSymbolFRINGE                  FactionTraitSymbol = "FRINGE"
	FactionTraitSymbolGUILD                   FactionTraitSymbol = "GUILD"
	FactionTraitSymbolIMPERIALISTIC           FactionTraitSymbol = "IMPERIALISTIC"
	FactionTraitSymbolINDEPENDENT             FactionTraitSymbol = "INDEPENDENT"
	FactionTraitSymbolINDUSTRIOUS             FactionTraitSymbol = "INDUSTRIOUS"
	FactionTraitSymbolINESCAPABLE             FactionTraitSymbol = "INESCAPABLE"
	FactionTraitSymbolINNOVATIVE              FactionTraitSymbol = "INNOVATIVE"
	FactionTraitSymbolINTELLIGENT             FactionTraitSymbol = "INTELLIGENT"
	FactionTraitSymbolISOLATED                FactionTraitSymbol = "ISOLATED"
	FactionTraitSymbolLOCALIZED               FactionTraitSymbol = "LOCALIZED"
	FactionTraitSymbolMILITARISTIC            FactionTraitSymbol = "MILITARISTIC"
	FactionTraitSymbolNOTABLE                 FactionTraitSymbol = "NOTABLE"
	FactionTraitSymbolPEACEFUL                FactionTraitSymbol = "PEACEFUL"
	FactionTraitSymbolPIRATES                 FactionTraitSymbol = "PIRATES"
	FactionTraitSymbolPROGRESSIVE             FactionTraitSymbol = "PROGRESSIVE"
	FactionTraitSymbolPROUD                   FactionTraitSymbol = "PROUD"
	FactionTraitSymbolRAIDERS                 FactionTraitSymbol = "RAIDERS"
	FactionTraitSymbolREBELLIOUS              FactionTraitSymbol = "REBELLIOUS"
	FactionTraitSymbolRESEARCHFOCUSED         FactionTraitSymbol = "RESEARCH_FOCUSED"
	FactionTraitSymbolRESOURCEFUL             FactionTraitSymbol = "RESOURCEFUL"
	FactionTraitSymbolSCAVENGERS              FactionTraitSymbol = "SCAVENGERS"
	FactionTraitSymbolSECRETIVE               FactionTraitSymbol = "SECRETIVE"
	FactionTraitSymbolSELFINTERESTED          FactionTraitSymbol = "SELF_INTERESTED"
	FactionTraitSymbolSELFSUFFICIENT          FactionTraitSymbol = "SELF_SUFFICIENT"
	FactionTraitSymbolSMUGGLERS               FactionTraitSymbol = "SMUGGLERS"
	FactionTraitSymbolSTRATEGIC               FactionTraitSymbol = "STRATEGIC"
	FactionTraitSymbolTECHNOLOGICALLYADVANCED FactionTraitSymbol = "TECHNOLOGICALLY_ADVANCED"
	FactionTraitSymbolTREASUREHUNTERS         FactionTraitSymbol = "TREASURE_HUNTERS"
	FactionTraitSymbolUNITED                  FactionTraitSymbol = "UNITED"
	FactionTraitSymbolUNPREDICTABLE           FactionTraitSymbol = "UNPREDICTABLE"
	FactionTraitSymbolVISIONARY               FactionTraitSymbol = "VISIONARY"
	FactionTraitSymbolWELCOMING               FactionTraitSymbol = "WELCOMING"
)

// Defines values for MarketTradeGoodType.
const (
	EXCHANGE MarketTradeGoodType = "EXCHANGE"
	EXPORT   MarketTradeGoodType = "EXPORT"
	IMPORT   MarketTradeGoodType = "IMPORT"
)

// Defines values for MarketTransactionType.
const (
	PURCHASE MarketTransactionType = "PURCHASE"
	SELL     MarketTransactionType = "SELL"
)

// Defines values for ShipConditionEventComponent.
const (
	ENGINE  ShipConditionEventComponent = "ENGINE"
	FRAME   ShipConditionEventComponent = "FRAME"
	REACTOR ShipConditionEventComponent = "REACTOR"
)

// Defines values for ShipConditionEventSymbol.
const (
	ATMOSPHERICENTRYHEAT             ShipConditionEventSymbol = "ATMOSPHERIC_ENTRY_HEAT"
	BEARINGLUBRICATIONFADE           ShipConditionEventSymbol = "BEARING_LUBRICATION_FADE"
	COOLANTLEAK                      ShipConditionEventSymbol = "COOLANT_LEAK"
	COOLANTSYSTEMAGEING              ShipConditionEventSymbol = "COOLANT_SYSTEM_AGEING"
	CORROSIVEMINERALCONTAMINATION    ShipConditionEventSymbol = "CORROSIVE_MINERAL_CONTAMINATION"
	DUSTMICROABRASIONS               ShipConditionEventSymbol = "DUST_MICROABRASIONS"
	ELECTROMAGNETICFIELDINTERFERENCE ShipConditionEventSymbol = "ELECTROMAGNETIC_FIELD_INTERFERENCE"
	ELECTROMAGNETICSURGEEFFECTS      ShipConditionEventSymbol = "ELECTROMAGNETIC_SURGE_EFFECTS"
	ENERGYSPIKEFROMMINERAL           ShipConditionEventSymbol = "ENERGY_SPIKE_FROM_MINERAL"
	EXHAUSTPORTCLOGGING              ShipConditionEventSymbol = "EXHAUST_PORT_CLOGGING"
	FUELEFFICIENCYDEGRADATION        ShipConditionEventSymbol = "FUEL_EFFICIENCY_DEGRADATION"
	HULLMICROMETEORITEDAMAGE         ShipConditionEventSymbol = "HULL_MICROMETEORITE_DAMAGE"
	HULLMICROMETEORITESTRIKES        ShipConditionEventSymbol = "HULL_MICROMETEORITE_STRIKES"
	IMPACTWITHEXTRACTEDDEBRIS        ShipConditionEventSymbol = "IMPACT_WITH_EXTRACTED_DEBRIS"
	MAGNETICFIELDDISRUPTION          ShipConditionEventSymbol = "MAGNETIC_FIELD_DISRUPTION"
	POWERDISTRIBUTIONFLUCTUATION     ShipConditionEventSymbol = "POWER_DISTRIBUTION_FLUCTUATION"
	PRESSUREDIFFERENTIALSTRESS       ShipConditionEventSymbol = "PRESSURE_DIFFERENTIAL_STRESS"
	REACTOROVERLOAD                  ShipConditionEventSymbol = "REACTOR_OVERLOAD"
	SENSORCALIBRATIONDRIFT           ShipConditionEventSymbol = "SENSOR_CALIBRATION_DRIFT"
	SOLARFLAREINTERFERENCE           ShipConditionEventSymbol = "SOLAR_FLARE_INTERFERENCE"
	SPACEDEBRISCOLLISION             ShipConditionEventSymbol = "SPACE_DEBRIS_COLLISION"
	STRUCTURALSTRESSFRACTURES        ShipConditionEventSymbol = "STRUCTURAL_STRESS_FRACTURES"
	THERMALEXPANSIONMISMATCH         ShipConditionEventSymbol = "THERMAL_EXPANSION_MISMATCH"
	THERMALSTRESS                    ShipConditionEventSymbol = "THERMAL_STRESS"
	THRUSTERNOZZLEWEAR               ShipConditionEventSymbol = "THRUSTER_NOZZLE_WEAR"
	VIBRATIONDAMAGEFROMDRILLING      ShipConditionEventSymbol = "VIBRATION_DAMAGE_FROM_DRILLING"
	VIBRATIONOVERLOAD                ShipConditionEventSymbol = "VIBRATION_OVERLOAD"
)

// Defines values for ShipCrewRotation.
const (
	RELAXED ShipCrewRotation = "RELAXED"
	STRICT  ShipCrewRotation = "STRICT"
)

// Defines values for ShipEngineSymbol.
const (
	ShipEngineSymbolENGINEHYPERDRIVEI   ShipEngineSymbol = "ENGINE_HYPER_DRIVE_I"
	ShipEngineSymbolENGINEIMPULSEDRIVEI ShipEngineSymbol = "ENGINE_IMPULSE_DRIVE_I"
	ShipEngineSymbolENGINEIONDRIVEI     ShipEngineSymbol = "ENGINE_ION_DRIVE_I"
	ShipEngineSymbolENGINEIONDRIVEII    ShipEngineSymbol = "ENGINE_ION_DRIVE_II"
)

// Defines values for ShipFrameSymbol.
const (
	FRAMECARRIER        ShipFrameSymbol = "FRAME_CARRIER"
	FRAMECRUISER        ShipFrameSymbol = "FRAME_CRUISER"
	FRAMEDESTROYER      ShipFrameSymbol = "FRAME_DESTROYER"
	FRAMEDRONE          ShipFrameSymbol = "FRAME_DRONE"
	FRAMEEXPLORER       ShipFrameSymbol = "FRAME_EXPLORER"
	FRAMEFIGHTER        ShipFrameSymbol = "FRAME_FIGHTER"
	FRAMEFRIGATE        ShipFrameSymbol = "FRAME_FRIGATE"
	FRAMEHEAVYFREIGHTER ShipFrameSymbol = "FRAME_HEAVY_FREIGHTER"
	FRAMEINTERCEPTOR    ShipFrameSymbol = "FRAME_INTERCEPTOR"
	FRAMELIGHTFREIGHTER ShipFrameSymbol = "FRAME_LIGHT_FREIGHTER"
	FRAMEMINER          ShipFrameSymbol = "FRAME_MINER"
	FRAMEPROBE          ShipFrameSymbol = "FRAME_PROBE"
	FRAMERACER          ShipFrameSymbol = "FRAME_RACER"
	FRAMESHUTTLE        ShipFrameSymbol = "FRAME_SHUTTLE"
	FRAMETRANSPORT      ShipFrameSymbol = "FRAME_TRANSPORT"
)

// Defines values for ShipModuleSymbol.
const (
	MODULECARGOHOLDI        ShipModuleSymbol = "MODULE_CARGO_HOLD_I"
	MODULECARGOHOLDII       ShipModuleSymbol = "MODULE_CARGO_HOLD_II"
	MODULECARGOHOLDIII      ShipModuleSymbol = "MODULE_CARGO_HOLD_III"
	MODULECREWQUARTERSI     ShipModuleSymbol = "MODULE_CREW_QUARTERS_I"
	MODULEENVOYQUARTERSI    ShipModuleSymbol = "MODULE_ENVOY_QUARTERS_I"
	MODULEFUELREFINERYI     ShipModuleSymbol = "MODULE_FUEL_REFINERY_I"
	MODULEGASPROCESSORI     ShipModuleSymbol = "MODULE_GAS_PROCESSOR_I"
	MODULEJUMPDRIVEI        ShipModuleSymbol = "MODULE_JUMP_DRIVE_I"
	MODULEJUMPDRIVEII       ShipModuleSymbol = "MODULE_JUMP_DRIVE_II"
	MODULEJUMPDRIVEIII      ShipModuleSymbol = "MODULE_JUMP_DRIVE_III"
	MODULEMICROREFINERYI    ShipModuleSymbol = "MODULE_MICRO_REFINERY_I"
	MODULEMINERALPROCESSORI ShipModuleSymbol = "MODULE_MINERAL_PROCESSOR_I"
	MODULEOREREFINERYI      ShipModuleSymbol = "MODULE_ORE_REFINERY_I"
	MODULEPASSENGERCABINI   ShipModuleSymbol = "MODULE_PASSENGER_CABIN_I"
	MODULESCIENCELABI       ShipModuleSymbol = "MODULE_SCIENCE_LAB_I"
	MODULESHIELDGENERATORI  ShipModuleSymbol = "MODULE_SHIELD_GENERATOR_I"
	MODULESHIELDGENERATORII ShipModuleSymbol = "MODULE_SHIELD_GENERATOR_II"
	MODULEWARPDRIVEI        ShipModuleSymbol = "MODULE_WARP_DRIVE_I"
	MODULEWARPDRIVEII       ShipModuleSymbol = "MODULE_WARP_DRIVE_II"
	MODULEWARPDRIVEIII      ShipModuleSymbol = "MODULE_WARP_DRIVE_III"
)

// Defines values for ShipMountDeposits.
const (
	ALUMINUMORE     ShipMountDeposits = "ALUMINUM_ORE"
	AMMONIAICE      ShipMountDeposits = "AMMONIA_ICE"
	COPPERORE       ShipMountDeposits = "COPPER_ORE"
	DIAMONDS        ShipMountDeposits = "DIAMONDS"
	GOLDORE         ShipMountDeposits = "GOLD_ORE"
	ICEWATER        ShipMountDeposits = "ICE_WATER"
	IRONORE         ShipMountDeposits = "IRON_ORE"
	MERITIUMORE     ShipMountDeposits = "MERITIUM_ORE"
	PLATINUMORE     ShipMountDeposits = "PLATINUM_ORE"
	PRECIOUSSTONES  ShipMountDeposits = "PRECIOUS_STONES"
	QUARTZSAND      ShipMountDeposits = "QUARTZ_SAND"
	SILICONCRYSTALS ShipMountDeposits = "SILICON_CRYSTALS"
	SILVERORE       ShipMountDeposits = "SILVER_ORE"
	URANITEORE      ShipMountDeposits = "URANITE_ORE"
)

// Defines values for ShipMountSymbol.
const (
	MOUNTGASSIPHONI       ShipMountSymbol = "MOUNT_GAS_SIPHON_I"
	MOUNTGASSIPHONII      ShipMountSymbol = "MOUNT_GAS_SIPHON_II"
	MOUNTGASSIPHONIII     ShipMountSymbol = "MOUNT_GAS_SIPHON_III"
	MOUNTLASERCANNONI     ShipMountSymbol = "MOUNT_LASER_CANNON_I"
	MOUNTMININGLASERI     ShipMountSymbol = "MOUNT_MINING_LASER_I"
	MOUNTMININGLASERII    ShipMountSymbol = "MOUNT_MINING_LASER_II"
	MOUNTMININGLASERIII   ShipMountSymbol = "MOUNT_MINING_LASER_III"
	MOUNTMISSILELAUNCHERI ShipMountSymbol = "MOUNT_MISSILE_LAUNCHER_I"
	MOUNTSENSORARRAYI     ShipMountSymbol = "MOUNT_SENSOR_ARRAY_I"
	MOUNTSENSORARRAYII    ShipMountSymbol = "MOUNT_SENSOR_ARRAY_II"
	MOUNTSENSORARRAYIII   ShipMountSymbol = "MOUNT_SENSOR_ARRAY_III"
	MOUNTSURVEYORI        ShipMountSymbol = "MOUNT_SURVEYOR_I"
	MOUNTSURVEYORII       ShipMountSymbol = "MOUNT_SURVEYOR_II"
	MOUNTSURVEYORIII      ShipMountSymbol = "MOUNT_SURVEYOR_III"
	MOUNTTURRETI          ShipMountSymbol = "MOUNT_TURRET_I"
)

// Defines values for ShipNavFlightMode.
const (
	BURN    ShipNavFlightMode = "BURN"
	CRUISE  ShipNavFlightMode = "CRUISE"
	DRIFT   ShipNavFlightMode = "DRIFT"
	STEALTH ShipNavFlightMode = "STEALTH"
)

// Defines values for ShipNavStatus.
const (
	DOCKED    ShipNavStatus = "DOCKED"
	INORBIT   ShipNavStatus = "IN_ORBIT"
	INTRANSIT ShipNavStatus = "IN_TRANSIT"
)

// Defines values for ShipReactorSymbol.
const (
	REACTORANTIMATTERI ShipReactorSymbol = "REACTOR_ANTIMATTER_I"
	REACTORCHEMICALI   ShipReactorSymbol = "REACTOR_CHEMICAL_I"
	REACTORFISSIONI    ShipReactorSymbol = "REACTOR_FISSION_I"
	REACTORFUSIONI     ShipReactorSymbol = "REACTOR_FUSION_I"
	REACTORSOLARI      ShipReactorSymbol = "REACTOR_SOLAR_I"
)

// Defines values for ShipRole.
const (
	ShipRoleCARRIER     ShipRole = "CARRIER"
	ShipRoleCOMMAND     ShipRole = "COMMAND"
	ShipRoleEXCAVATOR   ShipRole = "EXCAVATOR"
	ShipRoleEXPLORER    ShipRole = "EXPLORER"
	ShipRoleFABRICATOR  ShipRole = "FABRICATOR"
	ShipRoleHARVESTER   ShipRole = "HARVESTER"
	ShipRoleHAULER      ShipRole = "HAULER"
	ShipRoleINTERCEPTOR ShipRole = "INTERCEPTOR"
	ShipRolePATROL      ShipRole = "PATROL"
	ShipRoleREFINERY    ShipRole = "REFINERY"
	ShipRoleREPAIR      ShipRole = "REPAIR"
	ShipRoleSATELLITE   ShipRole = "SATELLITE"
	ShipRoleSURVEYOR    ShipRole = "SURVEYOR"
	ShipRoleTRANSPORT   ShipRole = "TRANSPORT"
)

// Defines values for ShipType.
const (
	SHIPCOMMANDFRIGATE    ShipType = "SHIP_COMMAND_FRIGATE"
	SHIPEXPLORER          ShipType = "SHIP_EXPLORER"
	SHIPHEAVYFREIGHTER    ShipType = "SHIP_HEAVY_FREIGHTER"
	SHIPINTERCEPTOR       ShipType = "SHIP_INTERCEPTOR"
	SHIPLIGHTHAULER       ShipType = "SHIP_LIGHT_HAULER"
	SHIPLIGHTSHUTTLE      ShipType = "SHIP_LIGHT_SHUTTLE"
	SHIPMININGDRONE       ShipType = "SHIP_MINING_DRONE"
	SHIPOREHOUND          ShipType = "SHIP_ORE_HOUND"
	SHIPPROBE             ShipType = "SHIP_PROBE"
	SHIPREFININGFREIGHTER ShipType = "SHIP_REFINING_FREIGHTER"
	SHIPSIPHONDRONE       ShipType = "SHIP_SIPHON_DRONE"
	SHIPSURVEYOR          ShipType = "SHIP_SURVEYOR"
)

// Defines values for SupplyLevel.
const (
	SupplyLevelABUNDANT SupplyLevel = "ABUNDANT"
	SupplyLevelHIGH     SupplyLevel = "HIGH"
	SupplyLevelLIMITED  SupplyLevel = "LIMITED"
	SupplyLevelMODERATE SupplyLevel = "MODERATE"
	SupplyLevelSCARCE   SupplyLevel = "SCARCE"
)

// Defines values for SurveySize.
const (
	SurveySizeLARGE    SurveySize = "LARGE"
	SurveySizeMODERATE SurveySize = "MODERATE"
	SurveySizeSMALL    SurveySize = "SMALL"
)

// Defines values for SystemType.
const (
	SystemTypeBLACKHOLE   SystemType = "BLACK_HOLE"
	SystemTypeBLUESTAR    SystemType = "BLUE_STAR"
	SystemTypeHYPERGIANT  SystemType = "HYPERGIANT"
	SystemTypeNEBULA      SystemType = "NEBULA"
	SystemTypeNEUTRONSTAR SystemType = "NEUTRON_STAR"
	SystemTypeORANGESTAR  SystemType = "ORANGE_STAR"
	SystemTypeREDSTAR     SystemType = "RED_STAR"
	SystemTypeUNSTABLE    SystemType = "UNSTABLE"
	SystemTypeWHITEDWARF  SystemType = "WHITE_DWARF"
	SystemTypeYOUNGSTAR   SystemType = "YOUNG_STAR"
)

// Defines values for TradeSymbol.
const (
	TradeSymbolADVANCEDCIRCUITRY       TradeSymbol = "ADVANCED_CIRCUITRY"
	TradeSymbolAIMAINFRAMES            TradeSymbol = "AI_MAINFRAMES"
	TradeSymbolALUMINUM                TradeSymbol = "ALUMINUM"
	TradeSymbolALUMINUMORE             TradeSymbol = "ALUMINUM_ORE"
	TradeSymbolAMMONIAICE              TradeSymbol = "AMMONIA_ICE"
	TradeSymbolAMMUNITION              TradeSymbol = "AMMUNITION"
	TradeSymbolANTIMATTER              TradeSymbol = "ANTIMATTER"
	TradeSymbolASSAULTRIFLES           TradeSymbol = "ASSAULT_RIFLES"
	TradeSymbolBIOCOMPOSITES           TradeSymbol = "BIOCOMPOSITES"
	TradeSymbolBOTANICALSPECIMENS      TradeSymbol = "BOTANICAL_SPECIMENS"
	TradeSymbolCLOTHING                TradeSymbol = "CLOTHING"
	TradeSymbolCOPPER                  TradeSymbol = "COPPER"
	TradeSymbolCOPPERORE               TradeSymbol = "COPPER_ORE"
	TradeSymbolCULTURALARTIFACTS       TradeSymbol = "CULTURAL_ARTIFACTS"
	TradeSymbolCYBERIMPLANTS           TradeSymbol = "CYBER_IMPLANTS"
	TradeSymbolDIAMONDS                TradeSymbol = "DIAMONDS"
	TradeSymbolDRUGS                   TradeSymbol = "DRUGS"
	TradeSymbolELECTRONICS             TradeSymbol = "ELECTRONICS"
	TradeSymbolENGINEHYPERDRIVEI       TradeSymbol = "ENGINE_HYPER_DRIVE_I"
	TradeSymbolENGINEIMPULSEDRIVEI     TradeSymbol = "ENGINE_IMPULSE_DRIVE_I"
	TradeSymbolENGINEIONDRIVEI         TradeSymbol = "ENGINE_ION_DRIVE_I"
	TradeSymbolENGINEIONDRIVEII        TradeSymbol = "ENGINE_ION_DRIVE_II"
	TradeSymbolEQUIPMENT               TradeSymbol = "EQUIPMENT"
	TradeSymbolEXOTICMATTER            TradeSymbol = "EXOTIC_MATTER"
	TradeSymbolEXPLOSIVES              TradeSymbol = "EXPLOSIVES"
	TradeSymbolFABMATS                 TradeSymbol = "FAB_MATS"
	TradeSymbolFABRICS                 TradeSymbol = "FABRICS"
	TradeSymbolFERTILIZERS             TradeSymbol = "FERTILIZERS"
	TradeSymbolFIREARMS                TradeSymbol = "FIREARMS"
	TradeSymbolFOOD                    TradeSymbol = "FOOD"
	TradeSymbolFRAMECARRIER            TradeSymbol = "FRAME_CARRIER"
	TradeSymbolFRAMECRUISER            TradeSymbol = "FRAME_CRUISER"
	TradeSymbolFRAMEDESTROYER          TradeSymbol = "FRAME_DESTROYER"
	TradeSymbolFRAMEDRONE              TradeSymbol = "FRAME_DRONE"
	TradeSymbolFRAMEEXPLORER           TradeSymbol = "FRAME_EXPLORER"
	TradeSymbolFRAMEFIGHTER            TradeSymbol = "FRAME_FIGHTER"
	TradeSymbolFRAMEFRIGATE            TradeSymbol = "FRAME_FRIGATE"
	TradeSymbolFRAMEHEAVYFREIGHTER     TradeSymbol = "FRAME_HEAVY_FREIGHTER"
	TradeSymbolFRAMEINTERCEPTOR        TradeSymbol = "FRAME_INTERCEPTOR"
	TradeSymbolFRAMELIGHTFREIGHTER     TradeSymbol = "FRAME_LIGHT_FREIGHTER"
	TradeSymbolFRAMEMINER              TradeSymbol = "FRAME_MINER"
	TradeSymbolFRAMEPROBE              TradeSymbol = "FRAME_PROBE"
	TradeSymbolFRAMERACER              TradeSymbol = "FRAME_RACER"
	TradeSymbolFRAMESHUTTLE            TradeSymbol = "FRAME_SHUTTLE"
	TradeSymbolFRAMETRANSPORT          TradeSymbol = "FRAME_TRANSPORT"
	TradeSymbolFUEL                    TradeSymbol = "FUEL"
	TradeSymbolGENETHERAPEUTICS        TradeSymbol = "GENE_THERAPEUTICS"
	TradeSymbolGOLD                    TradeSymbol = "GOLD"
	TradeSymbolGOLDORE                 TradeSymbol = "GOLD_ORE"
	TradeSymbolGRAVITONEMITTERS        TradeSymbol = "GRAVITON_EMITTERS"
	TradeSymbolHOLOGRAPHICS            TradeSymbol = "HOLOGRAPHICS"
	TradeSymbolHYDROCARBON             TradeSymbol = "HYDROCARBON"
	TradeSymbolICEWATER                TradeSymbol = "ICE_WATER"
	TradeSymbolIRON                    TradeSymbol = "IRON"
	TradeSymbolIRONORE                 TradeSymbol = "IRON_ORE"
	TradeSymbolJEWELRY                 TradeSymbol = "JEWELRY"
	TradeSymbolLABINSTRUMENTS          TradeSymbol = "LAB_INSTRUMENTS"
	TradeSymbolLASERRIFLES             TradeSymbol = "LASER_RIFLES"
	TradeSymbolLIQUIDHYDROGEN          TradeSymbol = "LIQUID_HYDROGEN"
	TradeSymbolLIQUIDNITROGEN          TradeSymbol = "LIQUID_NITROGEN"
	TradeSymbolMACHINERY               TradeSymbol = "MACHINERY"
	TradeSymbolMEDICINE                TradeSymbol = "MEDICINE"
	TradeSymbolMERITIUM                TradeSymbol = "MERITIUM"
	TradeSymbolMERITIUMORE             TradeSymbol = "MERITIUM_ORE"
	TradeSymbolMICROFUSIONGENERATORS   TradeSymbol = "MICRO_FUSION_GENERATORS"
	TradeSymbolMICROPROCESSORS         TradeSymbol = "MICROPROCESSORS"
	TradeSymbolMILITARYEQUIPMENT       TradeSymbol = "MILITARY_EQUIPMENT"
	TradeSymbolMODULECARGOHOLDI        TradeSymbol = "MODULE_CARGO_HOLD_I"
	TradeSymbolMODULECARGOHOLDII       TradeSymbol = "MODULE_CARGO_HOLD_II"
	TradeSymbolMODULECARGOHOLDIII      TradeSymbol = "MODULE_CARGO_HOLD_III"
	TradeSymbolMODULECREWQUARTERSI     TradeSymbol = "MODULE_CREW_QUARTERS_I"
	TradeSymbolMODULEENVOYQUARTERSI    TradeSymbol = "MODULE_ENVOY_QUARTERS_I"
	TradeSymbolMODULEFUELREFINERYI     TradeSymbol = "MODULE_FUEL_REFINERY_I"
	TradeSymbolMODULEGASPROCESSORI     TradeSymbol = "MODULE_GAS_PROCESSOR_I"
	TradeSymbolMODULEJUMPDRIVEI        TradeSymbol = "MODULE_JUMP_DRIVE_I"
	TradeSymbolMODULEJUMPDRIVEII       TradeSymbol = "MODULE_JUMP_DRIVE_II"
	TradeSymbolMODULEJUMPDRIVEIII      TradeSymbol = "MODULE_JUMP_DRIVE_III"
	TradeSymbolMODULEMICROREFINERYI    TradeSymbol = "MODULE_MICRO_REFINERY_I"
	TradeSymbolMODULEMINERALPROCESSORI TradeSymbol = "MODULE_MINERAL_PROCESSOR_I"
	TradeSymbolMODULEOREREFINERYI      TradeSymbol = "MODULE_ORE_REFINERY_I"
	TradeSymbolMODULEPASSENGERCABINI   TradeSymbol = "MODULE_PASSENGER_CABIN_I"
	TradeSymbolMODULESCIENCELABI       TradeSymbol = "MODULE_SCIENCE_LAB_I"
	TradeSymbolMODULESHIELDGENERATORI  TradeSymbol = "MODULE_SHIELD_GENERATOR_I"
	TradeSymbolMODULESHIELDGENERATORII TradeSymbol = "MODULE_SHIELD_GENERATOR_II"
	TradeSymbolMODULEWARPDRIVEI        TradeSymbol = "MODULE_WARP_DRIVE_I"
	TradeSymbolMODULEWARPDRIVEII       TradeSymbol = "MODULE_WARP_DRIVE_II"
	TradeSymbolMODULEWARPDRIVEIII      TradeSymbol = "MODULE_WARP_DRIVE_III"
	TradeSymbolMOODREGULATORS          TradeSymbol = "MOOD_REGULATORS"
	TradeSymbolMOUNTGASSIPHONI         TradeSymbol = "MOUNT_GAS_SIPHON_I"
	TradeSymbolMOUNTGASSIPHONII        TradeSymbol = "MOUNT_GAS_SIPHON_II"
	TradeSymbolMOUNTGASSIPHONIII       TradeSymbol = "MOUNT_GAS_SIPHON_III"
	TradeSymbolMOUNTLASERCANNONI       TradeSymbol = "MOUNT_LASER_CANNON_I"
	TradeSymbolMOUNTMININGLASERI       TradeSymbol = "MOUNT_MINING_LASER_I"
	TradeSymbolMOUNTMININGLASERII      TradeSymbol = "MOUNT_MINING_LASER_II"
	TradeSymbolMOUNTMININGLASERIII     TradeSymbol = "MOUNT_MINING_LASER_III"
	TradeSymbolMOUNTMISSILELAUNCHERI   TradeSymbol = "MOUNT_MISSILE_LAUNCHER_I"
	TradeSymbolMOUNTSENSORARRAYI       TradeSymbol = "MOUNT_SENSOR_ARRAY_I"
	TradeSymbolMOUNTSENSORARRAYII      TradeSymbol = "MOUNT_SENSOR_ARRAY_II"
	TradeSymbolMOUNTSENSORARRAYIII     TradeSymbol = "MOUNT_SENSOR_ARRAY_III"
	TradeSymbolMOUNTSURVEYORI          TradeSymbol = "MOUNT_SURVEYOR_I"
	TradeSymbolMOUNTSURVEYORII         TradeSymbol = "MOUNT_SURVEYOR_II"
	TradeSymbolMOUNTSURVEYORIII        TradeSymbol = "MOUNT_SURVEYOR_III"
	TradeSymbolMOUNTTURRETI            TradeSymbol = "MOUNT_TURRET_I"
	TradeSymbolNANOBOTS                TradeSymbol = "NANOBOTS"
	TradeSymbolNEURALCHIPS             TradeSymbol = "NEURAL_CHIPS"
	TradeSymbolNOVELLIFEFORMS          TradeSymbol = "NOVEL_LIFEFORMS"
	TradeSymbolPLASTICS                TradeSymbol = "PLASTICS"
	TradeSymbolPLATINUM                TradeSymbol = "PLATINUM"
	TradeSymbolPLATINUMORE             TradeSymbol = "PLATINUM_ORE"
	TradeSymbolPOLYNUCLEOTIDES         TradeSymbol = "POLYNUCLEOTIDES"
	TradeSymbolPRECIOUSSTONES          TradeSymbol = "PRECIOUS_STONES"
	TradeSymbolQUANTUMDRIVES           TradeSymbol = "QUANTUM_DRIVES"
	TradeSymbolQUANTUMSTABILIZERS      TradeSymbol = "QUANTUM_STABILIZERS"
	TradeSymbolQUARTZSAND              TradeSymbol = "QUARTZ_SAND"
	TradeSymbolREACTORANTIMATTERI      TradeSymbol = "REACTOR_ANTIMATTER_I"
	TradeSymbolREACTORCHEMICALI        TradeSymbol = "REACTOR_CHEMICAL_I"
	TradeSymbolREACTORFISSIONI         TradeSymbol = "REACTOR_FISSION_I"
	TradeSymbolREACTORFUSIONI          TradeSymbol = "REACTOR_FUSION_I"
	TradeSymbolREACTORSOLARI           TradeSymbol = "REACTOR_SOLAR_I"
	TradeSymbolRELICTECH               TradeSymbol = "RELIC_TECH"
	TradeSymbolROBOTICDRONES           TradeSymbol = "ROBOTIC_DRONES"
	TradeSymbolSHIPCOMMANDFRIGATE      TradeSymbol = "SHIP_COMMAND_FRIGATE"
	TradeSymbolSHIPEXPLORER            TradeSymbol = "SHIP_EXPLORER"
	TradeSymbolSHIPHEAVYFREIGHTER      TradeSymbol = "SHIP_HEAVY_FREIGHTER"
	TradeSymbolSHIPINTERCEPTOR         TradeSymbol = "SHIP_INTERCEPTOR"
	TradeSymbolSHIPLIGHTHAULER         TradeSymbol = "SHIP_LIGHT_HAULER"
	TradeSymbolSHIPLIGHTSHUTTLE        TradeSymbol = "SHIP_LIGHT_SHUTTLE"
	TradeSymbolSHIPMININGDRONE         TradeSymbol = "SHIP_MINING_DRONE"
	TradeSymbolSHIPOREHOUND            TradeSymbol = "SHIP_ORE_HOUND"
	TradeSymbolSHIPPARTS               TradeSymbol = "SHIP_PARTS"
	TradeSymbolSHIPPLATING             TradeSymbol = "SHIP_PLATING"
	TradeSymbolSHIPPROBE               TradeSymbol = "SHIP_PROBE"
	TradeSymbolSHIPREFININGFREIGHTER   TradeSymbol = "SHIP_REFINING_FREIGHTER"
	TradeSymbolSHIPSALVAGE             TradeSymbol = "SHIP_SALVAGE"
	TradeSymbolSHIPSIPHONDRONE         TradeSymbol = "SHIP_SIPHON_DRONE"
	TradeSymbolSHIPSURVEYOR            TradeSymbol = "SHIP_SURVEYOR"
	TradeSymbolSILICONCRYSTALS         TradeSymbol = "SILICON_CRYSTALS"
	TradeSymbolSILVER                  TradeSymbol = "SILVER"
	TradeSymbolSILVERORE               TradeSymbol = "SILVER_ORE"
	TradeSymbolSUPERGRAINS             TradeSymbol = "SUPERGRAINS"
	TradeSymbolURANITE                 TradeSymbol = "URANITE"
	TradeSymbolURANITEORE              TradeSymbol = "URANITE_ORE"
	TradeSymbolVIRALAGENTS             TradeSymbol = "VIRAL_AGENTS"
)

// Defines values for WaypointModifierSymbol.
const (
	WaypointModifierSymbolCIVILUNREST   WaypointModifierSymbol = "CIVIL_UNREST"
	WaypointModifierSymbolCRITICALLIMIT WaypointModifierSymbol = "CRITICAL_LIMIT"
	WaypointModifierSymbolRADIATIONLEAK WaypointModifierSymbol = "RADIATION_LEAK"
	WaypointModifierSymbolSTRIPPED      WaypointModifierSymbol = "STRIPPED"
	WaypointModifierSymbolUNSTABLE      WaypointModifierSymbol = "UNSTABLE"
)

// Defines values for WaypointTraitSymbol.
const (
	ASHCLOUDS             WaypointTraitSymbol = "ASH_CLOUDS"
	BARREN                WaypointTraitSymbol = "BARREN"
	BLACKMARKET           WaypointTraitSymbol = "BLACK_MARKET"
	BREATHABLEATMOSPHERE  WaypointTraitSymbol = "BREATHABLE_ATMOSPHERE"
	BUREAUCRATIC          WaypointTraitSymbol = "BUREAUCRATIC"
	CANYONS               WaypointTraitSymbol = "CANYONS"
	COMMONMETALDEPOSITS   WaypointTraitSymbol = "COMMON_METAL_DEPOSITS"
	CORROSIVEATMOSPHERE   WaypointTraitSymbol = "CORROSIVE_ATMOSPHERE"
	CORRUPT               WaypointTraitSymbol = "CORRUPT"
	CRUSHINGGRAVITY       WaypointTraitSymbol = "CRUSHING_GRAVITY"
	DEBRISCLUSTER         WaypointTraitSymbol = "DEBRIS_CLUSTER"
	DEEPCRATERS           WaypointTraitSymbol = "DEEP_CRATERS"
	DIVERSELIFE           WaypointTraitSymbol = "DIVERSE_LIFE"
	DRYSEABEDS            WaypointTraitSymbol = "DRY_SEABEDS"
	EXPLORATIONOUTPOST    WaypointTraitSymbol = "EXPLORATION_OUTPOST"
	EXPLOSIVEGASES        WaypointTraitSymbol = "EXPLOSIVE_GASES"
	EXTREMEPRESSURE       WaypointTraitSymbol = "EXTREME_PRESSURE"
	EXTREMETEMPERATURES   WaypointTraitSymbol = "EXTREME_TEMPERATURES"
	FOSSILS               WaypointTraitSymbol = "FOSSILS"
	FROZEN                WaypointTraitSymbol = "FROZEN"
	HIGHTECH              WaypointTraitSymbol = "HIGH_TECH"
	HOLLOWEDINTERIOR      WaypointTraitSymbol = "HOLLOWED_INTERIOR"
	ICECRYSTALS           WaypointTraitSymbol = "ICE_CRYSTALS"
	INDUSTRIAL            WaypointTraitSymbol = "INDUSTRIAL"
	JOVIAN                WaypointTraitSymbol = "JOVIAN"
	JUNGLE                WaypointTraitSymbol = "JUNGLE"
	MAGMASEAS             WaypointTraitSymbol = "MAGMA_SEAS"
	MARKETPLACE           WaypointTraitSymbol = "MARKETPLACE"
	MEGASTRUCTURES        WaypointTraitSymbol = "MEGA_STRUCTURES"
	METHANEPOOLS          WaypointTraitSymbol = "METHANE_POOLS"
	MICROGRAVITYANOMALIES WaypointTraitSymbol = "MICRO_GRAVITY_ANOMALIES"
	MILITARYBASE          WaypointTraitSymbol = "MILITARY_BASE"
	MINERALDEPOSITS       WaypointTraitSymbol = "MINERAL_DEPOSITS"
	MUTATEDFLORA          WaypointTraitSymbol = "MUTATED_FLORA"
	OCEAN                 WaypointTraitSymbol = "OCEAN"
	OUTPOST               WaypointTraitSymbol = "OUTPOST"
	OVERCROWDED           WaypointTraitSymbol = "OVERCROWDED"
	PERPETUALDAYLIGHT     WaypointTraitSymbol = "PERPETUAL_DAYLIGHT"
	PERPETUALOVERCAST     WaypointTraitSymbol = "PERPETUAL_OVERCAST"
	PIRATEBASE            WaypointTraitSymbol = "PIRATE_BASE"
	PRECIOUSMETALDEPOSITS WaypointTraitSymbol = "PRECIOUS_METAL_DEPOSITS"
	RADIOACTIVE           WaypointTraitSymbol = "RADIOACTIVE"
	RAREMETALDEPOSITS     WaypointTraitSymbol = "RARE_METAL_DEPOSITS"
	RESEARCHFACILITY      WaypointTraitSymbol = "RESEARCH_FACILITY"
	ROCKY                 WaypointTraitSymbol = "ROCKY"
	SALTFLATS             WaypointTraitSymbol = "SALT_FLATS"
	SCARCELIFE            WaypointTraitSymbol = "SCARCE_LIFE"
	SCATTEREDSETTLEMENTS  WaypointTraitSymbol = "SCATTERED_SETTLEMENTS"
	SHALLOWCRATERS        WaypointTraitSymbol = "SHALLOW_CRATERS"
	SHIPYARD              WaypointTraitSymbol = "SHIPYARD"
	SPRAWLINGCITIES       WaypointTraitSymbol = "SPRAWLING_CITIES"
	STRIPPED              WaypointTraitSymbol = "STRIPPED"
	STRONGGRAVITY         WaypointTraitSymbol = "STRONG_GRAVITY"
	STRONGMAGNETOSPHERE   WaypointTraitSymbol = "STRONG_MAGNETOSPHERE"
	SUPERVOLCANOES        WaypointTraitSymbol = "SUPERVOLCANOES"
	SURVEILLANCEOUTPOST   WaypointTraitSymbol = "SURVEILLANCE_OUTPOST"
	SWAMP                 WaypointTraitSymbol = "SWAMP"
	TEMPERATE             WaypointTraitSymbol = "TEMPERATE"
	TERRAFORMED           WaypointTraitSymbol = "TERRAFORMED"
	THINATMOSPHERE        WaypointTraitSymbol = "THIN_ATMOSPHERE"
	TOXICATMOSPHERE       WaypointTraitSymbol = "TOXIC_ATMOSPHERE"
	TRADINGHUB            WaypointTraitSymbol = "TRADING_HUB"
	UNCHARTED             WaypointTraitSymbol = "UNCHARTED"
	UNDERCONSTRUCTION     WaypointTraitSymbol = "UNDER_CONSTRUCTION"
	UNSTABLECOMPOSITION   WaypointTraitSymbol = "UNSTABLE_COMPOSITION"
	VASTRUINS             WaypointTraitSymbol = "VAST_RUINS"
	VIBRANTAURORAS        WaypointTraitSymbol = "VIBRANT_AURORAS"
	VOLCANIC              WaypointTraitSymbol = "VOLCANIC"
	WEAKGRAVITY           WaypointTraitSymbol = "WEAK_GRAVITY"
)

// Defines values for WaypointType.
const (
	ARTIFICIALGRAVITYWELL WaypointType = "ARTIFICIAL_GRAVITY_WELL"
	ASTEROID              WaypointType = "ASTEROID"
	ASTEROIDBASE          WaypointType = "ASTEROID_BASE"
	ASTEROIDFIELD         WaypointType = "ASTEROID_FIELD"
	DEBRISFIELD           WaypointType = "DEBRIS_FIELD"
	ENGINEEREDASTEROID    WaypointType = "ENGINEERED_ASTEROID"
	FUELSTATION           WaypointType = "FUEL_STATION"
	GASGIANT              WaypointType = "GAS_GIANT"
	GRAVITYWELL           WaypointType = "GRAVITY_WELL"
	JUMPGATE              WaypointType = "JUMP_GATE"
	MOON                  WaypointType = "MOON"
	NEBULA                WaypointType = "NEBULA"
	ORBITALSTATION        WaypointType = "ORBITAL_STATION"
	PLANET                WaypointType = "PLANET"
)

// Defines values for ShipRefineJSONBodyProduce.
const (
	ALUMINUM ShipRefineJSONBodyProduce = "ALUMINUM"
	COPPER   ShipRefineJSONBodyProduce = "COPPER"
	FUEL     ShipRefineJSONBodyProduce = "FUEL"
	GOLD     ShipRefineJSONBodyProduce = "GOLD"
	IRON     ShipRefineJSONBodyProduce = "IRON"
	MERITIUM ShipRefineJSONBodyProduce = "MERITIUM"
	PLATINUM ShipRefineJSONBodyProduce = "PLATINUM"
	SILVER   ShipRefineJSONBodyProduce = "SILVER"
	URANITE  ShipRefineJSONBodyProduce = "URANITE"
)

// ActivityLevel The activity level of a trade good. If the good is an import, this represents how strong consumption is. If the good is an export, this represents how strong the production is for the good. When activity is strong, consumption or production is near maximum capacity. When activity is weak, consumption or production is near minimum capacity.
type ActivityLevel string

// Agent Agent details.
type Agent struct {
	// AccountId Account ID that is tied to this agent. Only included on your own agent.
	AccountId *string `json:"accountId,omitempty"`

	// Credits The number of credits the agent has available. Credits can be negative if funds have been overdrawn.
	Credits int64 `json:"credits"`

	// Headquarters The headquarters of the agent.
	Headquarters string `json:"headquarters"`

	// ShipCount How many ships are owned by the agent.
	ShipCount int `json:"shipCount"`

	// StartingFaction The faction the agent started with.
	StartingFaction string `json:"startingFaction"`

	// Symbol Symbol of the agent.
	Symbol string `json:"symbol"`
}

// Chart The chart of a system or waypoint, which makes the location visible to other agents.
type Chart struct {
	// SubmittedBy The agent that submitted the chart for this waypoint.
	SubmittedBy *string `json:"submittedBy,omitempty"`

	// SubmittedOn The time the chart for this waypoint was submitted.
	SubmittedOn *time.Time `json:"submittedOn,omitempty"`

	// WaypointSymbol The symbol of the waypoint.
	WaypointSymbol *WaypointSymbol `json:"waypointSymbol,omitempty"`
}

// Construction The construction details of a waypoint.
type Construction struct {
	// IsComplete Whether the waypoint has been constructed.
	IsComplete bool `json:"isComplete"`

	// Materials The materials required to construct the waypoint.
	Materials []ConstructionMaterial `json:"materials"`

	// Symbol The symbol of the waypoint.
	Symbol string `json:"symbol"`
}

// ConstructionMaterial The details of the required construction materials for a given waypoint under construction.
type ConstructionMaterial struct {
	// Fulfilled The number of units fulfilled toward the required amount.
	Fulfilled int `json:"fulfilled"`

	// Required The number of units required.
	Required int `json:"required"`

	// TradeSymbol The good's symbol.
	TradeSymbol TradeSymbol `json:"tradeSymbol"`
}

// Contract Contract details.
type Contract struct {
	// Accepted Whether the contract has been accepted by the agent
	Accepted bool `json:"accepted"`

	// DeadlineToAccept The time at which the contract is no longer available to be accepted
	DeadlineToAccept *time.Time `json:"deadlineToAccept,omitempty"`

	// Expiration Deprecated in favor of deadlineToAccept
	// Deprecated:
	Expiration time.Time `json:"expiration"`

	// FactionSymbol The symbol of the faction that this contract is for.
	FactionSymbol string `json:"factionSymbol"`

	// Fulfilled Whether the contract has been fulfilled
	Fulfilled bool `json:"fulfilled"`

	// Id ID of the contract.
	Id string `json:"id"`

	// Terms The terms to fulfill the contract.
	Terms ContractTerms `json:"terms"`

	// Type Type of contract.
	Type ContractType `json:"type"`
}

// ContractType Type of contract.
type ContractType string

// ContractDeliverGood The details of a delivery contract. Includes the type of good, units needed, and the destination.
type ContractDeliverGood struct {
	// DestinationSymbol The destination where goods need to be delivered.
	DestinationSymbol string `json:"destinationSymbol"`

	// TradeSymbol The symbol of the trade good to deliver.
	TradeSymbol string `json:"tradeSymbol"`

	// UnitsFulfilled The number of units fulfilled on this contract.
	UnitsFulfilled int `json:"unitsFulfilled"`

	// UnitsRequired The number of units that need to be delivered on this contract.
	UnitsRequired int `json:"unitsRequired"`
}

// ContractPayment Payments for the contract.
type ContractPayment struct {
	// OnAccepted The amount of credits received up front for accepting the contract.
	OnAccepted int `json:"onAccepted"`

	// OnFulfilled The amount of credits received when the contract is fulfilled.
	OnFulfilled int `json:"onFulfilled"`
}

// ContractTerms The terms to fulfill the contract.
type ContractTerms struct {
	// Deadline The deadline for the contract.
	Deadline time.Time `json:"deadline"`

	// Deliver The cargo that needs to be delivered to fulfill the contract.
	Deliver *[]ContractDeliverGood `json:"deliver,omitempty"`

	// Payment Payments for the contract.
	Payment ContractPayment `json:"payment"`
}

// Cooldown A cooldown is a period of time in which a ship cannot perform certain actions.
type Cooldown struct {
	// Expiration The date and time when the cooldown expires in ISO 8601 format
	Expiration *time.Time `json:"expiration,omitempty"`

	// RemainingSeconds The remaining duration of the cooldown in seconds
	RemainingSeconds int `json:"remainingSeconds"`

	// ShipSymbol The symbol of the ship that is on cooldown
	ShipSymbol string `json:"shipSymbol"`

	// TotalSeconds The total duration of the cooldown in seconds
	TotalSeconds int `json:"totalSeconds"`
}

// Extraction Extraction details.
type Extraction struct {
	// ShipSymbol Symbol of the ship that executed the extraction.
	ShipSymbol string `json:"shipSymbol"`

	// Yield A yield from the extraction operation.
	Yield ExtractionYield `json:"yield"`
}

// ExtractionYield A yield from the extraction operation.
type ExtractionYield struct {
	// Symbol The good's symbol.
	Symbol TradeSymbol `json:"symbol"`

	// Units The number of units extracted that were placed into the ship's cargo hold.
	Units int `json:"units"`
}

// Faction Faction details.
type Faction struct {
	// Description Description of the faction.
	Description string `json:"description"`

	// Headquarters The waypoint in which the faction's HQ is located in.
	Headquarters string `json:"headquarters"`

	// IsRecruiting Whether or not the faction is currently recruiting new agents.
	IsRecruiting bool `json:"isRecruiting"`

	// Name Name of the faction.
	Name string `json:"name"`

	// Symbol The symbol of the faction.
	Symbol FactionSymbol `json:"symbol"`

	// Traits List of traits that define this faction.
	Traits []FactionTrait `json:"traits"`
}

// FactionSymbol The symbol of the faction.
type FactionSymbol string

// FactionTrait defines model for FactionTrait.
type FactionTrait struct {
	// Description A description of the trait.
	Description string `json:"description"`

	// Name The name of the trait.
	Name string `json:"name"`

	// Symbol The unique identifier of the trait.
	Symbol FactionTraitSymbol `json:"symbol"`
}

// FactionTraitSymbol The unique identifier of the trait.
type FactionTraitSymbol string

// JumpGate defines model for JumpGate.
type JumpGate struct {
	// Connections All the gates that are connected to this waypoint.
	Connections []string `json:"connections"`

	// Symbol The symbol of the waypoint.
	Symbol WaypointSymbol `json:"symbol"`
}

// Market defines model for Market.
type Market struct {
	// Exchange The list of goods that are bought and sold between agents at this market.
	Exchange []TradeGood `json:"exchange"`

	// Exports The list of goods that are exported from this market.
	Exports []TradeGood `json:"exports"`

	// Imports The list of goods that are sought as imports in this market.
	Imports []TradeGood `json:"imports"`

	// Symbol The symbol of the market. The symbol is the same as the waypoint where the market is located.
	Symbol string `json:"symbol"`

	// TradeGoods The list of goods that are traded at this market. Visible only when a ship is present at the market.
	TradeGoods *[]MarketTradeGood `json:"tradeGoods,omitempty"`

	// Transactions The list of recent transactions at this market. Visible only when a ship is present at the market.
	Transactions *[]MarketTransaction `json:"transactions,omitempty"`
}

// MarketTradeGood defines model for MarketTradeGood.
type MarketTradeGood struct {
	// Activity The activity level of a trade good. If the good is an import, this represents how strong consumption is. If the good is an export, this represents how strong the production is for the good. When activity is strong, consumption or production is near maximum capacity. When activity is weak, consumption or production is near minimum capacity.
	Activity *ActivityLevel `json:"activity,omitempty"`

	// PurchasePrice The price at which this good can be purchased from the market.
	PurchasePrice int `json:"purchasePrice"`

	// SellPrice The price at which this good can be sold to the market.
	SellPrice int `json:"sellPrice"`

	// Supply The supply level of a trade good.
	Supply SupplyLevel `json:"supply"`

	// Symbol The good's symbol.
	Symbol TradeSymbol `json:"symbol"`

	// TradeVolume This is the maximum number of units that can be purchased or sold at this market in a single trade for this good. Trade volume also gives an indication of price volatility. A market with a low trade volume will have large price swings, while high trade volume will be more resilient to price changes.
	TradeVolume int `json:"tradeVolume"`

	// Type The type of trade good (export, import, or exchange).
	Type MarketTradeGoodType `json:"type"`
}

// MarketTradeGoodType The type of trade good (export, import, or exchange).
type MarketTradeGoodType string

// MarketTransaction Result of a transaction with a market.
type MarketTransaction struct {
	// PricePerUnit The price per unit of the transaction.
	PricePerUnit int `json:"pricePerUnit"`

	// ShipSymbol The symbol of the ship that made the transaction.
	ShipSymbol string `json:"shipSymbol"`

	// Timestamp The timestamp of the transaction.
	Timestamp time.Time `json:"timestamp"`

	// TotalPrice The total price of the transaction.
	TotalPrice int `json:"totalPrice"`

	// TradeSymbol The symbol of the trade good.
	TradeSymbol string `json:"tradeSymbol"`

	// Type The type of transaction.
	Type MarketTransactionType `json:"type"`

	// Units The number of units of the transaction.
	Units int `json:"units"`

	// WaypointSymbol The symbol of the waypoint.
	WaypointSymbol WaypointSymbol `json:"waypointSymbol"`
}

// MarketTransactionType The type of transaction.
type MarketTransactionType string

// Meta Meta details for pagination.
type Meta struct {
	// Limit The amount of items in each page. Limits how many items can be fetched at once.
	Limit int `json:"limit"`

	// Page A page denotes an amount of items, offset from the first item. Each page holds an amount of items equal to the `limit`.
	Page int `json:"page"`

	// Total Shows the total amount of items of this kind that exist.
	Total int `json:"total"`
}

// RepairTransaction Result of a repair transaction.
type RepairTransaction struct {
	// ShipSymbol The symbol of the ship.
	ShipSymbol string `json:"shipSymbol"`

	// Timestamp The timestamp of the transaction.
	Timestamp time.Time `json:"timestamp"`

	// TotalPrice The total price of the transaction.
	TotalPrice int `json:"totalPrice"`

	// WaypointSymbol The symbol of the waypoint.
	WaypointSymbol WaypointSymbol `json:"waypointSymbol"`
}

// ScannedShip The ship that was scanned. Details include information about the ship that could be detected by the scanner.
type ScannedShip struct {
	// Engine The engine of the ship.
	Engine struct {
		// Symbol The symbol of the engine.
		Symbol string `json:"symbol"`
	} `json:"engine"`

	// Frame The frame of the ship.
	Frame *struct {
		// Symbol The symbol of the frame.
		Symbol string `json:"symbol"`
	} `json:"frame,omitempty"`

	// Mounts List of mounts installed in the ship.
	Mounts *[]struct {
		// Symbol The symbol of the mount.
		Symbol string `json:"symbol"`
	} `json:"mounts,omitempty"`

	// Nav The navigation information of the ship.
	Nav ShipNav `json:"nav"`

	// Reactor The reactor of the ship.
	Reactor *struct {
		// Symbol The symbol of the reactor.
		Symbol string `json:"symbol"`
	} `json:"reactor,omitempty"`

	// Registration The public registration information of the ship
	Registration ShipRegistration `json:"registration"`

	// Symbol The globally unique identifier of the ship.
	Symbol string `json:"symbol"`
}

// ScannedSystem Details of a system was that scanned.
type ScannedSystem struct {
	// Distance The system's distance from the scanning ship.
	Distance int `json:"distance"`

	// SectorSymbol Symbol of the system's sector.
	SectorSymbol string `json:"sectorSymbol"`

	// Symbol Symbol of the system.
	Symbol string `json:"symbol"`

	// Type The type of system.
	Type SystemType `json:"type"`

	// X Position in the universe in the x axis.
	X int `json:"x"`

	// Y Position in the universe in the y axis.
	Y int `json:"y"`
}

// ScannedWaypoint A waypoint that was scanned by a ship.
type ScannedWaypoint struct {
	// Chart The chart of a system or waypoint, which makes the location visible to other agents.
	Chart *Chart `json:"chart,omitempty"`

	// Faction The faction that controls the waypoint.
	Faction *WaypointFaction `json:"faction,omitempty"`

	// Orbitals List of waypoints that orbit this waypoint.
	Orbitals []WaypointOrbital `json:"orbitals"`

	// Symbol The symbol of the waypoint.
	Symbol WaypointSymbol `json:"symbol"`

	// SystemSymbol The symbol of the system.
	SystemSymbol SystemSymbol `json:"systemSymbol"`

	// Traits The traits of the waypoint.
	Traits []WaypointTrait `json:"traits"`

	// Type The type of waypoint.
	Type WaypointType `json:"type"`

	// X Position in the universe in the x axis.
	X int `json:"x"`

	// Y Position in the universe in the y axis.
	Y int `json:"y"`
}

// ScrapTransaction Result of a scrap transaction.
type ScrapTransaction struct {
	// ShipSymbol The symbol of the ship.
	ShipSymbol string `json:"shipSymbol"`

	// Timestamp The timestamp of the transaction.
	Timestamp time.Time `json:"timestamp"`

	// TotalPrice The total price of the transaction.
	TotalPrice int `json:"totalPrice"`

	// WaypointSymbol The symbol of the waypoint.
	WaypointSymbol WaypointSymbol `json:"waypointSymbol"`
}

// Ship Ship details.
type Ship struct {
	// Cargo Ship cargo details.
	Cargo ShipCargo `json:"cargo"`

	// Cooldown A cooldown is a period of time in which a ship cannot perform certain actions.
	Cooldown Cooldown `json:"cooldown"`

	// Crew The ship's crew service and maintain the ship's systems and equipment.
	Crew ShipCrew `json:"crew"`

	// Engine The engine determines how quickly a ship travels between waypoints.
	Engine ShipEngine `json:"engine"`

	// Frame The frame of the ship. The frame determines the number of modules and mounting points of the ship, as well as base fuel capacity. As the condition of the frame takes more wear, the ship will become more sluggish and less maneuverable.
	Frame ShipFrame `json:"frame"`

	// Fuel Details of the ship's fuel tanks including how much fuel was consumed during the last transit or action.
	Fuel ShipFuel `json:"fuel"`

	// Modules Modules installed in this ship.
	Modules []ShipModule `json:"modules"`

	// Mounts Mounts installed in this ship.
	Mounts []ShipMount `json:"mounts"`

	// Nav The navigation information of the ship.
	Nav ShipNav `json:"nav"`

	// Reactor The reactor of the ship. The reactor is responsible for powering the ship's systems and weapons.
	Reactor ShipReactor `json:"reactor"`

	// Registration The public registration information of the ship
	Registration ShipRegistration `json:"registration"`

	// Symbol The globally unique identifier of the ship in the following format: `[AGENT_SYMBOL]-[HEX_ID]`
	Symbol string `json:"symbol"`
}

// ShipCargo Ship cargo details.
type ShipCargo struct {
	// Capacity The max number of items that can be stored in the cargo hold.
	Capacity int `json:"capacity"`

	// Inventory The items currently in the cargo hold.
	Inventory []ShipCargoItem `json:"inventory"`

	// Units The number of items currently stored in the cargo hold.
	Units int `json:"units"`
}

// ShipCargoItem The type of cargo item and the number of units.
type ShipCargoItem struct {
	// Description The description of the cargo item type.
	Description string `json:"description"`

	// Name The name of the cargo item type.
	Name string `json:"name"`

	// Symbol The good's symbol.
	Symbol TradeSymbol `json:"symbol"`

	// Units The number of units of the cargo item.
	Units int `json:"units"`
}

// ShipComponentCondition The repairable condition of a component. A value of 0 indicates the component needs significant repairs, while a value of 1 indicates the component is in near perfect condition. As the condition of a component is repaired, the overall integrity of the component decreases.
type ShipComponentCondition = float64

// ShipComponentIntegrity The overall integrity of the component, which determines the performance of the component. A value of 0 indicates that the component is almost completely degraded, while a value of 1 indicates that the component is in near perfect condition. The integrity of the component is non-repairable, and represents permanent wear over time.
type ShipComponentIntegrity = float64

// ShipConditionEvent An event that represents damage or wear to a ship's reactor, frame, or engine, reducing the condition of the ship.
type ShipConditionEvent struct {
	Component ShipConditionEventComponent `json:"component"`

	// Description A description of the event.
	Description string `json:"description"`

	// Name The name of the event.
	Name   string                   `json:"name"`
	Symbol ShipConditionEventSymbol `json:"symbol"`
}

// ShipConditionEventComponent defines model for ShipConditionEvent.Component.
type ShipConditionEventComponent string

// ShipConditionEventSymbol defines model for ShipConditionEvent.Symbol.
type ShipConditionEventSymbol string

// ShipCrew The ship's crew service and maintain the ship's systems and equipment.
type ShipCrew struct {
	// Capacity The maximum number of crew members the ship can support.
	Capacity int `json:"capacity"`

	// Current The current number of crew members on the ship.
	Current int `json:"current"`

	// Morale A rough measure of the crew's morale. A higher morale means the crew is happier and more productive. A lower morale means the ship is more prone to accidents.
	Morale int `json:"morale"`

	// Required The minimum number of crew members required to maintain the ship.
	Required int `json:"required"`

	// Rotation The rotation of crew shifts. A stricter shift improves the ship's performance. A more relaxed shift improves the crew's morale.
	Rotation ShipCrewRotation `json:"rotation"`

	// Wages The amount of credits per crew member paid per hour. Wages are paid when a ship docks at a civilized waypoint.
	Wages int `json:"wages"`
}

// ShipCrewRotation The rotation of crew shifts. A stricter shift improves the ship's performance. A more relaxed shift improves the crew's morale.
type ShipCrewRotation string

// ShipEngine The engine determines how quickly a ship travels between waypoints.
type ShipEngine struct {
	// Condition The repairable condition of a component. A value of 0 indicates the component needs significant repairs, while a value of 1 indicates the component is in near perfect condition. As the condition of a component is repaired, the overall integrity of the component decreases.
	Condition ShipComponentCondition `json:"condition"`

	// Description The description of the engine.
	Description string `json:"description"`

	// Integrity The overall integrity of the component, which determines the performance of the component. A value of 0 indicates that the component is almost completely degraded, while a value of 1 indicates that the component is in near perfect condition. The integrity of the component is non-repairable, and represents permanent wear over time.
	Integrity ShipComponentIntegrity `json:"integrity"`

	// Name The name of the engine.
	Name string `json:"name"`

	// Requirements The requirements for installation on a ship
	Requirements ShipRequirements `json:"requirements"`

	// Speed The speed stat of this engine. The higher the speed, the faster a ship can travel from one point to another. Reduces the time of arrival when navigating the ship.
	Speed int `json:"speed"`

	// Symbol The symbol of the engine.
	Symbol ShipEngineSymbol `json:"symbol"`
}

// ShipEngineSymbol The symbol of the engine.
type ShipEngineSymbol string

// ShipFrame The frame of the ship. The frame determines the number of modules and mounting points of the ship, as well as base fuel capacity. As the condition of the frame takes more wear, the ship will become more sluggish and less maneuverable.
type ShipFrame struct {
	// Condition The repairable condition of a component. A value of 0 indicates the component needs significant repairs, while a value of 1 indicates the component is in near perfect condition. As the condition of a component is repaired, the overall integrity of the component decreases.
	Condition ShipComponentCondition `json:"condition"`

	// Description Description of the frame.
	Description string `json:"description"`

	// FuelCapacity The maximum amount of fuel that can be stored in this ship. When refueling, the ship will be refueled to this amount.
	FuelCapacity int `json:"fuelCapacity"`

	// Integrity The overall integrity of the component, which determines the performance of the component. A value of 0 indicates that the component is almost completely degraded, while a value of 1 indicates that the component is in near perfect condition. The integrity of the component is non-repairable, and represents permanent wear over time.
	Integrity ShipComponentIntegrity `json:"integrity"`

	// ModuleSlots The amount of slots that can be dedicated to modules installed in the ship. Each installed module take up a number of slots, and once there are no more slots, no new modules can be installed.
	ModuleSlots int `json:"moduleSlots"`

	// MountingPoints The amount of slots that can be dedicated to mounts installed in the ship. Each installed mount takes up a number of points, and once there are no more points remaining, no new mounts can be installed.
	MountingPoints int `json:"mountingPoints"`

	// Name Name of the frame.
	Name string `json:"name"`

	// Requirements The requirements for installation on a ship
	Requirements ShipRequirements `json:"requirements"`

	// Symbol Symbol of the frame.
	Symbol ShipFrameSymbol `json:"symbol"`
}

// ShipFrameSymbol Symbol of the frame.
type ShipFrameSymbol string

// ShipFuel Details of the ship's fuel tanks including how much fuel was consumed during the last transit or action.
type ShipFuel struct {
	// Capacity The maximum amount of fuel the ship's tanks can hold.
	Capacity int `json:"capacity"`

	// Consumed An object that only shows up when an action has consumed fuel in the process. Shows the fuel consumption data.
	Consumed *struct {
		// Amount The amount of fuel consumed by the most recent transit or action.
		Amount int `json:"amount"`

		// Timestamp The time at which the fuel was consumed.
		Timestamp time.Time `json:"timestamp"`
	} `json:"consumed,omitempty"`

	// Current The current amount of fuel in the ship's tanks.
	Current int `json:"current"`
}

// ShipModificationTransaction Result of a transaction for a ship modification, such as installing a mount or a module.
type ShipModificationTransaction struct {
	// ShipSymbol The symbol of the ship that made the transaction.
	ShipSymbol string `json:"shipSymbol"`

	// Timestamp The timestamp of the transaction.
	Timestamp time.Time `json:"timestamp"`

	// TotalPrice The total price of the transaction.
	TotalPrice int `json:"totalPrice"`

	// TradeSymbol The symbol of the trade good.
	TradeSymbol string `json:"tradeSymbol"`

	// WaypointSymbol The symbol of the waypoint where the transaction took place.
	WaypointSymbol string `json:"waypointSymbol"`
}

// ShipModule A module can be installed in a ship and provides a set of capabilities such as storage space or quarters for crew. Module installations are permanent.
type ShipModule struct {
	// Capacity Modules that provide capacity, such as cargo hold or crew quarters will show this value to denote how much of a bonus the module grants.
	Capacity *int `json:"capacity,omitempty"`

	// Description Description of this module.
	Description string `json:"description"`

	// Name Name of this module.
	Name string `json:"name"`

	// Range Modules that have a range will such as a sensor array show this value to denote how far can the module reach with its capabilities.
	Range *int `json:"range,omitempty"`

	// Requirements The requirements for installation on a ship
	Requirements ShipRequirements `json:"requirements"`

	// Symbol The symbol of the module.
	Symbol ShipModuleSymbol `json:"symbol"`
}

// ShipModuleSymbol The symbol of the module.
type ShipModuleSymbol string

// ShipMount A mount is installed on the exterier of a ship.
type ShipMount struct {
	// Deposits Mounts that have this value denote what goods can be produced from using the mount.
	Deposits *[]ShipMountDeposits `json:"deposits,omitempty"`

	// Description Description of this mount.
	Description *string `json:"description,omitempty"`

	// Name Name of this mount.
	Name string `json:"name"`

	// Requirements The requirements for installation on a ship
	Requirements ShipRequirements `json:"requirements"`

	// Strength Mounts that have this value, such as mining lasers, denote how powerful this mount's capabilities are.
	Strength *int `json:"strength,omitempty"`

	// Symbol Symbo of this mount.
	Symbol ShipMountSymbol `json:"symbol"`
}

// ShipMountDeposits defines model for ShipMount.Deposits.
type ShipMountDeposits string

// ShipMountSymbol Symbo of this mount.
type ShipMountSymbol string

// ShipNav The navigation information of the ship.
type ShipNav struct {
	// FlightMode The ship's set speed when traveling between waypoints or systems.
	FlightMode ShipNavFlightMode `json:"flightMode"`

	// Route The routing information for the ship's most recent transit or current location.
	Route ShipNavRoute `json:"route"`

	// Status The current status of the ship
	Status ShipNavStatus `json:"status"`

	// SystemSymbol The symbol of the system.
	SystemSymbol SystemSymbol `json:"systemSymbol"`

	// WaypointSymbol The symbol of the waypoint.
	WaypointSymbol WaypointSymbol `json:"waypointSymbol"`
}

// ShipNavFlightMode The ship's set speed when traveling between waypoints or systems.
type ShipNavFlightMode string

// ShipNavRoute The routing information for the ship's most recent transit or current location.
type ShipNavRoute struct {
	// Arrival The date time of the ship's arrival. If the ship is in-transit, this is the expected time of arrival.
	Arrival time.Time `json:"arrival"`

	// DepartureTime The date time of the ship's departure.
	DepartureTime time.Time `json:"departureTime"`

	// Destination The destination or departure of a ships nav route.
	Destination ShipNavRouteWaypoint `json:"destination"`

	// Origin The destination or departure of a ships nav route.
	Origin ShipNavRouteWaypoint `json:"origin"`
}

// ShipNavRouteWaypoint The destination or departure of a ships nav route.
type ShipNavRouteWaypoint struct {
	// Symbol The symbol of the waypoint.
	Symbol string `json:"symbol"`

	// SystemSymbol The symbol of the system.
	SystemSymbol SystemSymbol `json:"systemSymbol"`

	// Type The type of waypoint.
	Type WaypointType `json:"type"`

	// X Position in the universe in the x axis.
	X int `json:"x"`

	// Y Position in the universe in the y axis.
	Y int `json:"y"`
}

// ShipNavStatus The current status of the ship
type ShipNavStatus string

// ShipReactor The reactor of the ship. The reactor is responsible for powering the ship's systems and weapons.
type ShipReactor struct {
	// Condition The repairable condition of a component. A value of 0 indicates the component needs significant repairs, while a value of 1 indicates the component is in near perfect condition. As the condition of a component is repaired, the overall integrity of the component decreases.
	Condition ShipComponentCondition `json:"condition"`

	// Description Description of the reactor.
	Description string `json:"description"`

	// Integrity The overall integrity of the component, which determines the performance of the component. A value of 0 indicates that the component is almost completely degraded, while a value of 1 indicates that the component is in near perfect condition. The integrity of the component is non-repairable, and represents permanent wear over time.
	Integrity ShipComponentIntegrity `json:"integrity"`

	// Name Name of the reactor.
	Name string `json:"name"`

	// PowerOutput The amount of power provided by this reactor. The more power a reactor provides to the ship, the lower the cooldown it gets when using a module or mount that taxes the ship's power.
	PowerOutput int `json:"powerOutput"`

	// Requirements The requirements for installation on a ship
	Requirements ShipRequirements `json:"requirements"`

	// Symbol Symbol of the reactor.
	Symbol ShipReactorSymbol `json:"symbol"`
}

// ShipReactorSymbol Symbol of the reactor.
type ShipReactorSymbol string

// ShipRegistration The public registration information of the ship
type ShipRegistration struct {
	// FactionSymbol The symbol of the faction the ship is registered with
	FactionSymbol string `json:"factionSymbol"`

	// Name The agent's registered name of the ship
	Name string `json:"name"`

	// Role The registered role of the ship
	Role ShipRole `json:"role"`
}

// ShipRequirements The requirements for installation on a ship
type ShipRequirements struct {
	// Crew The number of crew required for operation.
	Crew *int `json:"crew,omitempty"`

	// Power The amount of power required from the reactor.
	Power *int `json:"power,omitempty"`

	// Slots The number of module slots required for installation.
	Slots *int `json:"slots,omitempty"`
}

// ShipRole The registered role of the ship
type ShipRole string

// ShipType Type of ship
type ShipType string

// Shipyard defines model for Shipyard.
type Shipyard struct {
	// ModificationsFee The fee to modify a ship at this shipyard. This includes installing or removing modules and mounts on a ship. In the case of mounts, the fee is a flat rate per mount. In the case of modules, the fee is per slot the module occupies.
	ModificationsFee int `json:"modificationsFee"`

	// ShipTypes The list of ship types available for purchase at this shipyard.
	ShipTypes []struct {
		// Type Type of ship
		Type ShipType `json:"type"`
	} `json:"shipTypes"`

	// Ships The ships that are currently available for purchase at the shipyard.
	Ships *[]ShipyardShip `json:"ships,omitempty"`

	// Symbol The symbol of the shipyard. The symbol is the same as the waypoint where the shipyard is located.
	Symbol string `json:"symbol"`

	// Transactions The list of recent transactions at this shipyard.
	Transactions *[]ShipyardTransaction `json:"transactions,omitempty"`
}

// ShipyardShip defines model for ShipyardShip.
type ShipyardShip struct {
	// Activity The activity level of a trade good. If the good is an import, this represents how strong consumption is. If the good is an export, this represents how strong the production is for the good. When activity is strong, consumption or production is near maximum capacity. When activity is weak, consumption or production is near minimum capacity.
	Activity *ActivityLevel `json:"activity,omitempty"`
	Crew     struct {
		Capacity int `json:"capacity"`
		Required int `json:"required"`
	} `json:"crew"`
	Description string `json:"description"`

	// Engine The engine determines how quickly a ship travels between waypoints.
	Engine ShipEngine `json:"engine"`

	// Frame The frame of the ship. The frame determines the number of modules and mounting points of the ship, as well as base fuel capacity. As the condition of the frame takes more wear, the ship will become more sluggish and less maneuverable.
	Frame         ShipFrame    `json:"frame"`
	Modules       []ShipModule `json:"modules"`
	Mounts        []ShipMount  `json:"mounts"`
	Name          string       `json:"name"`
	PurchasePrice int          `json:"purchasePrice"`

	// Reactor The reactor of the ship. The reactor is responsible for powering the ship's systems and weapons.
	Reactor ShipReactor `json:"reactor"`

	// Supply The supply level of a trade good.
	Supply SupplyLevel `json:"supply"`

	// Type Type of ship
	Type ShipType `json:"type"`
}

// ShipyardTransaction Results of a transaction with a shipyard.
type ShipyardTransaction struct {
	// AgentSymbol The symbol of the agent that made the transaction.
	AgentSymbol string `json:"agentSymbol"`

	// Price The price of the transaction.
	Price int `json:"price"`

	// ShipSymbol The symbol of the ship that was the subject of the transaction.
	// Deprecated:
	ShipSymbol string `json:"shipSymbol"`

	// ShipType The symbol of the ship that was the subject of the transaction.
	ShipType string `json:"shipType"`

	// Timestamp The timestamp of the transaction.
	Timestamp time.Time `json:"timestamp"`

	// WaypointSymbol The symbol of the waypoint.
	WaypointSymbol WaypointSymbol `json:"waypointSymbol"`
}

// Siphon Siphon details.
type Siphon struct {
	// ShipSymbol Symbol of the ship that executed the siphon.
	ShipSymbol string `json:"shipSymbol"`

	// Yield A yield from the siphon operation.
	Yield SiphonYield `json:"yield"`
}

// SiphonYield A yield from the siphon operation.
type SiphonYield struct {
	// Symbol The good's symbol.
	Symbol TradeSymbol `json:"symbol"`

	// Units The number of units siphoned that were placed into the ship's cargo hold.
	Units int `json:"units"`
}

// SupplyLevel The supply level of a trade good.
type SupplyLevel string

// Survey A resource survey of a waypoint, detailing a specific extraction location and the types of resources that can be found there.
type Survey struct {
	// Deposits A list of deposits that can be found at this location. A ship will extract one of these deposits when using this survey in an extraction request. If multiple deposits of the same type are present, the chance of extracting that deposit is increased.
	Deposits []SurveyDeposit `json:"deposits"`

	// Expiration The date and time when the survey expires. After this date and time, the survey will no longer be available for extraction.
	Expiration time.Time `json:"expiration"`

	// Signature A unique signature for the location of this survey. This signature is verified when attempting an extraction using this survey.
	Signature string `json:"signature"`

	// Size The size of the deposit. This value indicates how much can be extracted from the survey before it is exhausted.
	Size SurveySize `json:"size"`

	// Symbol The symbol of the waypoint that this survey is for.
	Symbol string `json:"symbol"`
}

// SurveySize The size of the deposit. This value indicates how much can be extracted from the survey before it is exhausted.
type SurveySize string

// SurveyDeposit A surveyed deposit of a mineral or resource available for extraction.
type SurveyDeposit struct {
	// Symbol The symbol of the deposit.
	Symbol string `json:"symbol"`
}

// System defines model for System.
type System struct {
	// Factions Factions that control this system.
	Factions []SystemFaction `json:"factions"`

	// SectorSymbol The symbol of the sector.
	SectorSymbol string `json:"sectorSymbol"`

	// Symbol The symbol of the system.
	Symbol string `json:"symbol"`

	// Type The type of system.
	Type SystemType `json:"type"`

	// Waypoints Waypoints in this system.
	Waypoints []SystemWaypoint `json:"waypoints"`

	// X Relative position of the system in the sector in the x axis.
	X int `json:"x"`

	// Y Relative position of the system in the sector in the y axis.
	Y int `json:"y"`
}

// SystemFaction defines model for SystemFaction.
type SystemFaction struct {
	// Symbol The symbol of the faction.
	Symbol FactionSymbol `json:"symbol"`
}

// SystemSymbol The symbol of the system.
type SystemSymbol = string

// SystemType The type of system.
type SystemType string

// SystemWaypoint defines model for SystemWaypoint.
type SystemWaypoint struct {
	// Orbitals Waypoints that orbit this waypoint.
	Orbitals []WaypointOrbital `json:"orbitals"`

	// Orbits The symbol of the parent waypoint, if this waypoint is in orbit around another waypoint. Otherwise this value is undefined.
	Orbits *string `json:"orbits,omitempty"`

	// Symbol The symbol of the waypoint.
	Symbol WaypointSymbol `json:"symbol"`

	// Type The type of waypoint.
	Type WaypointType `json:"type"`

	// X Relative position of the waypoint on the system's x axis. This is not an absolute position in the universe.
	X int `json:"x"`

	// Y Relative position of the waypoint on the system's y axis. This is not an absolute position in the universe.
	Y int `json:"y"`
}

// TradeGood A good that can be traded for other goods or currency.
type TradeGood struct {
	// Description The description of the good.
	Description string `json:"description"`

	// Name The name of the good.
	Name string `json:"name"`

	// Symbol The good's symbol.
	Symbol TradeSymbol `json:"symbol"`
}

// TradeSymbol The good's symbol.
type TradeSymbol string

// Waypoint A waypoint is a location that ships can travel to such as a Planet, Moon or Space Station.
type Waypoint struct {
	// Chart The chart of a system or waypoint, which makes the location visible to other agents.
	Chart *Chart `json:"chart,omitempty"`

	// Faction The faction that controls the waypoint.
	Faction *WaypointFaction `json:"faction,omitempty"`

	// IsUnderConstruction True if the waypoint is under construction.
	IsUnderConstruction bool `json:"isUnderConstruction"`

	// Modifiers The modifiers of the waypoint.
	Modifiers *[]WaypointModifier `json:"modifiers,omitempty"`

	// Orbitals Waypoints that orbit this waypoint.
	Orbitals []WaypointOrbital `json:"orbitals"`

	// Orbits The symbol of the parent waypoint, if this waypoint is in orbit around another waypoint. Otherwise this value is undefined.
	Orbits *string `json:"orbits,omitempty"`

	// Symbol The symbol of the waypoint.
	Symbol WaypointSymbol `json:"symbol"`

	// SystemSymbol The symbol of the system.
	SystemSymbol SystemSymbol `json:"systemSymbol"`

	// Traits The traits of the waypoint.
	Traits []WaypointTrait `json:"traits"`

	// Type The type of waypoint.
	Type WaypointType `json:"type"`

	// X Relative position of the waypoint on the system's x axis. This is not an absolute position in the universe.
	X int `json:"x"`

	// Y Relative position of the waypoint on the system's y axis. This is not an absolute position in the universe.
	Y int `json:"y"`
}

// WaypointFaction The faction that controls the waypoint.
type WaypointFaction struct {
	// Symbol The symbol of the faction.
	Symbol FactionSymbol `json:"symbol"`
}

// WaypointModifier defines model for WaypointModifier.
type WaypointModifier struct {
	// Description A description of the trait.
	Description string `json:"description"`

	// Name The name of the trait.
	Name string `json:"name"`

	// Symbol The unique identifier of the modifier.
	Symbol WaypointModifierSymbol `json:"symbol"`
}

// WaypointModifierSymbol The unique identifier of the modifier.
type WaypointModifierSymbol string

// WaypointOrbital An orbital is another waypoint that orbits a parent waypoint.
type WaypointOrbital struct {
	// Symbol The symbol of the orbiting waypoint.
	Symbol string `json:"symbol"`
}

// WaypointSymbol The symbol of the waypoint.
type WaypointSymbol = string

// WaypointTrait defines model for WaypointTrait.
type WaypointTrait struct {
	// Description A description of the trait.
	Description string `json:"description"`

	// Name The name of the trait.
	Name string `json:"name"`

	// Symbol The unique identifier of the trait.
	Symbol WaypointTraitSymbol `json:"symbol"`
}

// WaypointTraitSymbol The unique identifier of the trait.
type WaypointTraitSymbol string

// WaypointType The type of waypoint.
type WaypointType string

// GetAgentsParams defines parameters for GetAgents.
type GetAgentsParams struct {
	// Page What entry offset to request
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// Limit How many entries to return per page
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetFactionsParams defines parameters for GetFactions.
type GetFactionsParams struct {
	// Page What entry offset to request
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// Limit How many entries to return per page
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetContractsParams defines parameters for GetContracts.
type GetContractsParams struct {
	// Page What entry offset to request
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// Limit How many entries to return per page
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// DeliverContractJSONBody defines parameters for DeliverContract.
type DeliverContractJSONBody struct {
	// ShipSymbol Symbol of a ship located in the destination to deliver a contract and that has a good to deliver in its cargo.
	ShipSymbol string `json:"shipSymbol"`

	// TradeSymbol The symbol of the good to deliver.
	TradeSymbol string `json:"tradeSymbol"`

	// Units Amount of units to deliver.
	Units int `json:"units"`
}

// GetMyShipsParams defines parameters for GetMyShips.
type GetMyShipsParams struct {
	// Page What entry offset to request
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// Limit How many entries to return per page
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// PurchaseShipJSONBody defines parameters for PurchaseShip.
type PurchaseShipJSONBody struct {
	// ShipType Type of ship
	ShipType ShipType `json:"shipType"`

	// WaypointSymbol The symbol of the waypoint you want to purchase the ship at.
	WaypointSymbol string `json:"waypointSymbol"`
}

// ExtractResourcesJSONBody defines parameters for ExtractResources.
type ExtractResourcesJSONBody struct {
	// Survey A resource survey of a waypoint, detailing a specific extraction location and the types of resources that can be found there.
	Survey *Survey `json:"survey,omitempty"`
}

// JettisonJSONBody defines parameters for Jettison.
type JettisonJSONBody struct {
	// Symbol The good's symbol.
	Symbol TradeSymbol `json:"symbol"`

	// Units Amount of units to jettison of this good.
	Units int `json:"units"`
}

// JumpShipJSONBody defines parameters for JumpShip.
type JumpShipJSONBody struct {
	// WaypointSymbol The symbol of the waypoint to jump to. The destination must be a connected waypoint.
	WaypointSymbol string `json:"waypointSymbol"`
}

// InstallMountJSONBody defines parameters for InstallMount.
type InstallMountJSONBody struct {
	Symbol string `json:"symbol"`
}

// RemoveMountJSONBody defines parameters for RemoveMount.
type RemoveMountJSONBody struct {
	// Symbol The symbol of the mount to remove.
	Symbol string `json:"symbol"`
}

// PatchShipNavJSONBody defines parameters for PatchShipNav.
type PatchShipNavJSONBody struct {
	// FlightMode The ship's set speed when traveling between waypoints or systems.
	FlightMode *ShipNavFlightMode `json:"flightMode,omitempty"`
}

// NavigateShipJSONBody defines parameters for NavigateShip.
type NavigateShipJSONBody struct {
	// WaypointSymbol The target destination.
	WaypointSymbol string `json:"waypointSymbol"`
}

// PurchaseCargoJSONBody defines parameters for PurchaseCargo.
type PurchaseCargoJSONBody struct {
	// Symbol The good's symbol.
	Symbol TradeSymbol `json:"symbol"`

	// Units Amounts of units to purchase.
	Units int `json:"units"`
}

// ShipRefineJSONBody defines parameters for ShipRefine.
type ShipRefineJSONBody struct {
	// Produce The type of good to produce out of the refining process.
	Produce ShipRefineJSONBodyProduce `json:"produce"`
}

// ShipRefineJSONBodyProduce defines parameters for ShipRefine.
type ShipRefineJSONBodyProduce string

// RefuelShipJSONBody defines parameters for RefuelShip.
type RefuelShipJSONBody struct {
	// FromCargo Wether to use the FUEL thats in your cargo or not. Default: false
	FromCargo *bool `json:"fromCargo,omitempty"`

	// Units The amount of fuel to fill in the ship's tanks. When not specified, the ship will be refueled to its maximum fuel capacity. If the amount specified is greater than the ship's remaining capacity, the ship will only be refueled to its maximum fuel capacity. The amount specified is not in market units but in ship fuel units.
	Units *int `json:"units,omitempty"`
}

// SellCargoJSONBody defines parameters for SellCargo.
type SellCargoJSONBody struct {
	// Symbol The good's symbol.
	Symbol TradeSymbol `json:"symbol"`

	// Units Amounts of units to sell of the selected good.
	Units int `json:"units"`
}

// TransferCargoJSONBody defines parameters for TransferCargo.
type TransferCargoJSONBody struct {
	// ShipSymbol The symbol of the ship to transfer to.
	ShipSymbol string `json:"shipSymbol"`

	// TradeSymbol The good's symbol.
	TradeSymbol TradeSymbol `json:"tradeSymbol"`

	// Units Amount of units to transfer.
	Units int `json:"units"`
}

// WarpShipJSONBody defines parameters for WarpShip.
type WarpShipJSONBody struct {
	// WaypointSymbol The target destination.
	WaypointSymbol string `json:"waypointSymbol"`
}

// RegisterJSONBody defines parameters for Register.
type RegisterJSONBody struct {
	// Email Your email address. This is used if you reserved your call sign between resets.
	Email *string `json:"email,omitempty"`

	// Faction The symbol of the faction.
	Faction FactionSymbol `json:"faction"`

	// Symbol Your desired agent symbol. This will be a unique name used to represent your agent, and will be the prefix for your ships.
	Symbol string `json:"symbol"`
}

// GetSystemsParams defines parameters for GetSystems.
type GetSystemsParams struct {
	// Page What entry offset to request
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// Limit How many entries to return per page
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetSystemWaypointsParams defines parameters for GetSystemWaypoints.
type GetSystemWaypointsParams struct {
	// Page What entry offset to request
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// Limit How many entries to return per page
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Type Filter waypoints by type.
	Type *WaypointType `form:"type,omitempty" json:"type,omitempty"`

	// Traits Filter waypoints by one or more traits.
	Traits *struct {
		union json.RawMessage
	} `form:"traits,omitempty" json:"traits,omitempty"`
}

// GetSystemWaypointsParamsTraits1 defines parameters for GetSystemWaypoints.
type GetSystemWaypointsParamsTraits1 = []WaypointTraitSymbol

// SupplyConstructionJSONBody defines parameters for SupplyConstruction.
type SupplyConstructionJSONBody struct {
	// ShipSymbol Symbol of the ship to use.
	ShipSymbol string `json:"shipSymbol"`

	// TradeSymbol The symbol of the good to supply.
	TradeSymbol string `json:"tradeSymbol"`

	// Units Amount of units to supply.
	Units int `json:"units"`
}

// DeliverContractJSONRequestBody defines body for DeliverContract for application/json ContentType.
type DeliverContractJSONRequestBody DeliverContractJSONBody

// PurchaseShipJSONRequestBody defines body for PurchaseShip for application/json ContentType.
type PurchaseShipJSONRequestBody PurchaseShipJSONBody

// ExtractResourcesJSONRequestBody defines body for ExtractResources for application/json ContentType.
type ExtractResourcesJSONRequestBody ExtractResourcesJSONBody

// ExtractResourcesWithSurveyJSONRequestBody defines body for ExtractResourcesWithSurvey for application/json ContentType.
type ExtractResourcesWithSurveyJSONRequestBody = Survey

// JettisonJSONRequestBody defines body for Jettison for application/json ContentType.
type JettisonJSONRequestBody JettisonJSONBody

// JumpShipJSONRequestBody defines body for JumpShip for application/json ContentType.
type JumpShipJSONRequestBody JumpShipJSONBody

// InstallMountJSONRequestBody defines body for InstallMount for application/json ContentType.
type InstallMountJSONRequestBody InstallMountJSONBody

// RemoveMountJSONRequestBody defines body for RemoveMount for application/json ContentType.
type RemoveMountJSONRequestBody RemoveMountJSONBody

// PatchShipNavJSONRequestBody defines body for PatchShipNav for application/json ContentType.
type PatchShipNavJSONRequestBody PatchShipNavJSONBody

// NavigateShipJSONRequestBody defines body for NavigateShip for application/json ContentType.
type NavigateShipJSONRequestBody NavigateShipJSONBody

// PurchaseCargoJSONRequestBody defines body for PurchaseCargo for application/json ContentType.
type PurchaseCargoJSONRequestBody PurchaseCargoJSONBody

// ShipRefineJSONRequestBody defines body for ShipRefine for application/json ContentType.
type ShipRefineJSONRequestBody ShipRefineJSONBody

// RefuelShipJSONRequestBody defines body for RefuelShip for application/json ContentType.
type RefuelShipJSONRequestBody RefuelShipJSONBody

// SellCargoJSONRequestBody defines body for SellCargo for application/json ContentType.
type SellCargoJSONRequestBody SellCargoJSONBody

// TransferCargoJSONRequestBody defines body for TransferCargo for application/json ContentType.
type TransferCargoJSONRequestBody TransferCargoJSONBody

// WarpShipJSONRequestBody defines body for WarpShip for application/json ContentType.
type WarpShipJSONRequestBody WarpShipJSONBody

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody RegisterJSONBody

// SupplyConstructionJSONRequestBody defines body for SupplyConstruction for application/json ContentType.
type SupplyConstructionJSONRequestBody SupplyConstructionJSONBody
