package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.53

import (
	"context"
	"fmt"

	"github.com/stnokott/spacetrader-server/internal/graph/loaders"
	"github.com/stnokott/spacetrader-server/internal/graph/model"
)

// System is the resolver for the system field.
func (r *shipResolver) System(ctx context.Context, obj *model.Ship) (*model.System, error) {
	system, err := loaders.GetSystem(ctx, obj.SystemID)
	if err != nil {
		return nil, fmt.Errorf("querying system for ship %s: %w", obj.Name, err)
	}
	return system, nil
}

// Waypoint is the resolver for the waypoint field.
func (r *shipResolver) Waypoint(ctx context.Context, obj *model.Ship) (*model.Waypoint, error) {
	waypoint, err := loaders.GetWaypoint(ctx, obj.WaypointID)
	if err != nil {
		return nil, fmt.Errorf("querying waypoint for ship %s: %w", obj.Name, err)
	}
	return waypoint, nil
}

// Ship returns ShipResolver implementation.
func (r *Resolver) Ship() ShipResolver { return &shipResolver{r} }

type shipResolver struct{ *Resolver }
