package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.53

import (
	"context"
	"fmt"

	"github.com/stnokott/spacetrader-server/internal/graph/model"
)

// ConnectedSystems is the resolver for the connectedSystems field.
func (r *systemResolver) ConnectedSystems(ctx context.Context, obj *model.System) ([]string, error) {
	rows, err := r.db.GetConnectedSystemNames(ctx, obj.Name)
	if err != nil {
		return nil, fmt.Errorf("querying connected systems for system %s: %w", obj.Name, err)
	}
	return rows, nil
}

// System returns SystemResolver implementation.
func (r *Resolver) System() SystemResolver { return &systemResolver{r} }

type systemResolver struct{ *Resolver }
