package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.53

import (
	"context"
	"fmt"

	"github.com/stnokott/spacetrader-server/internal/graph/loaders"
	"github.com/stnokott/spacetrader-server/internal/graph/model"
)

// System is the resolver for the system field.
func (r *waypointResolver) System(ctx context.Context, obj *model.Waypoint) (*model.System, error) {
	system, err := loaders.GetSystem(ctx, obj.SystemID)
	if err != nil {
		return nil, fmt.Errorf("querying system for waypoint %s: %w", obj.Name, err)
	}
	return system, nil
}

// ConnectedTo is the resolver for the connectedTo field.
func (r *waypointResolver) ConnectedTo(ctx context.Context, obj *model.Waypoint) ([]*model.Waypoint, error) {
	waypointIDs, err := r.db.GetConnectionsForWaypoint(ctx, obj.Name)
	if err != nil {
		return nil, fmt.Errorf("querying jumpgate connections for waypoint %s: %w", obj.Name, err)
	}

	out := make([]*model.Waypoint, len(waypointIDs))
	loader := loaders.For(ctx)
	for i, wpID := range waypointIDs {
		if out[i], err = loader.WaypointsLoader.Load(ctx, wpID); err != nil {
			return nil, err
		}
	}
	return out, nil
}

// Waypoint returns WaypointResolver implementation.
func (r *Resolver) Waypoint() WaypointResolver { return &waypointResolver{r} }

type waypointResolver struct{ *Resolver }
